metadata:
  display-name: OpenSearch Helm chart
  short-description: OpenSearch is a distributed, RESTful search and analytics engine designed for a wide range of use cases.
  featured: false
  home-url: https://opensearch.org
  categories:
    - databases-and-storage
    - monitoring-and-observability
