image:
  repository: ${alertmanager.registry}/${alertmanager.repository}
  tag: ${alertmanager.tag}@${alertmanager.digest}

configmapReload:
  image:
    repository: ${prometheus-config-reloader.registry}/${prometheus-config-reloader.repository}
    tag: ${prometheus-config-reloader.tag}@${prometheus-config-reloader.digest}
