metadata:
  display-name: Dex Helm chart
  short-description: OpenID Connect (OIDC) identity and OAuth 2.0 provider with pluggable connectors
  featured: false
  home-url: https://dexidp.io/
  categories:
    - security
