metadata:
  display-name: Grafana Agent Helm chart
  short-description: Lightweight telemetry collector for metrics, logs, traces, and profiles
  featured: false
  home-url: https://grafana.com/oss/agent/
  categories:
    - monitoring-and-observability
