image:
  registry: ${traefik.registry}
  repository: ${traefik.repository}
  tag: ${traefik.tag}@${traefik.digest}

global:
  azure:
    images:
      proxy:
        registry: ${traefik.registry}
        image: ${traefik.repository}
        tag: ${traefik.tag}@${traefik.digest}
