metadata:
  display-name: Prometheus Adapter
  short-description: |
    Prometheus Adapter implements the custom.metrics.k8s.io and external.metrics.k8s.io APIs for Kubernetes
    HPA and VPA, exposing metrics from Prometheus.
  featured: false
  home-url: https://github.com/kubernetes-sigs/prometheus-adapter
  categories:
    - monitoring-and-observability
