# syntax=dhi.io/build:2-helm3

name: VictoriaMetrics Alerts Helm chart 0.x
image: dhi.io/victoriametrics-alert-chart
variant: helm
tags:
  - 0.31.0
platforms:
  - linux/amd64
vars:
  ALERTMANAGER_REFERENCE: dhi/alertmanager:0.31.0-debian13@sha256:e6e12a22fa3abebb5097581c03060bdbf2e01beccd69d8a427e7da5b5f1988d8
  CHART_COMMIT_SHA: 5c1debc9b82344b174477e045a2d400b55a4edee
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_REFERENCE: dhi/helm:3.20.0-debian13-dev@sha256:83f437b3254d4db06d42aa7e1e8e6043ae1feacadf709e6b12b925345c91468a
  SEMVER_MAJOR_MINOR_VERSION: "0.31"
  SEMVER_MAJOR_VERSION: "0"
  SEMVER_VERSION: 0.31.0
  VERSION: 0.31.0
  VMALERT_REFERENCE: dhi/victoriametrics-vmalert:1.135.0-debian13@sha256:315eddae79d15d55b2d5c5b4214b834be833473652b02cc78d6c51a67c1beb58
  VMALERT_TAG: 1.129.1
contents:
  builds:
    - name: victoriametrics-alert-chart
      uses: dhi.io/helm:3.20.0-debian13-dev@sha256:83f437b3254d4db06d42aa7e1e8e6043ae1feacadf709e6b12b925345c91468a
      contents:
        files:
          - url: git+https://github.com/VictoriaMetrics/helm-charts.git#victoria-metrics-alert-0.31.0
            checksum: 5c1debc9b82344b174477e045a2d400b55a4edee
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/victoria-metrics-alert
          with:
            chart:
              appRef: victoriametrics-vmalert
              description: Docker Hardened Images Helm chart for VictoriaMetrics Alert
              images:
                - name: victoriametrics-vmalert
                  ref: dhi/victoriametrics-vmalert:1.135.0-debian13@sha256:315eddae79d15d55b2d5c5b4214b834be833473652b02cc78d6c51a67c1beb58
                - name: alertmanager
                  ref: dhi/alertmanager:0.31.0-debian13@sha256:e6e12a22fa3abebb5097581c03060bdbf2e01beccd69d8a427e7da5b5f1988d8
              name: victoriametrics-alert-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/VictoriaMetrics/helm-charts
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/victoria-metrics-alert
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: update dependencies
          uses: helm/cmd@v1
          privileged: true
          with:
            chart: ${source.dir}/helm-charts/charts/victoria-metrics-alert
            cmd: dependency update
        - name: lint
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/charts
          with:
            chart: victoria-metrics-alert
            cmd: lint .
        - name: package
          uses: helm/package@v1
          with:
            chart: ${source.dir}/helm-charts/charts/victoria-metrics-alert
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/victoriametrics-alert/config
