# syntax=dhi.io/build:2-helm3

name: VictoriaMetrics Alerts Helm chart 0.x
image: dhi.io/victoriametrics-alert-chart
variant: helm
tags:
  - 0.30.0
platforms:
  - linux/amd64
vars:
  ALERTMANAGER_REFERENCE: dhi/alertmanager:0.30.1-debian13@sha256:1257335b00114ea16bc543ca74a78884ddacf50bb47bc1f3460accac34eca321
  CHART_COMMIT_SHA: fb1f9c11825a53d3a4a8ed89724977edcdf19382
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_REFERENCE: dhi/helm:3.20.0-debian13-dev@sha256:7cb2e3261500133ea8b5a670b731b6d200e5637b9b1d8451ccc759c358fca0dc
  SEMVER_MAJOR_MINOR_VERSION: "0.30"
  SEMVER_MAJOR_VERSION: "0"
  SEMVER_VERSION: 0.30.0
  VERSION: 0.30.0
  VMALERT_REFERENCE: dhi/victoriametrics-vmalert:1.134.0-debian13@sha256:c412d72040f1c259f3be5a2c98690c6cb0a7eb534f90e5c5c75fe77674ed5218
  VMALERT_TAG: 1.129.1
contents:
  builds:
    - name: victoriametrics-alert-chart
      uses: dhi.io/helm:3.20.0-debian13-dev@sha256:7cb2e3261500133ea8b5a670b731b6d200e5637b9b1d8451ccc759c358fca0dc
      contents:
        files:
          - url: git+https://github.com/VictoriaMetrics/helm-charts.git#victoria-metrics-alert-0.30.0
            checksum: fb1f9c11825a53d3a4a8ed89724977edcdf19382
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/victoria-metrics-alert
          with:
            chart:
              appRef: victoriametrics-vmalert
              description: Docker Hardened Images Helm chart for VictoriaMetrics Alert
              images:
                - name: victoriametrics-vmalert
                  ref: dhi/victoriametrics-vmalert:1.134.0-debian13@sha256:c412d72040f1c259f3be5a2c98690c6cb0a7eb534f90e5c5c75fe77674ed5218
                - name: alertmanager
                  ref: dhi/alertmanager:0.30.1-debian13@sha256:1257335b00114ea16bc543ca74a78884ddacf50bb47bc1f3460accac34eca321
              name: victoriametrics-alert-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/VictoriaMetrics/helm-charts
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/victoria-metrics-alert
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: update dependencies
          uses: helm/cmd@v1
          privileged: true
          with:
            chart: ${source.dir}/helm-charts/charts/victoria-metrics-alert
            cmd: dependency update
        - name: lint
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/charts
          with:
            chart: victoria-metrics-alert
            cmd: lint .
        - name: package
          uses: helm/package@v1
          with:
            chart: ${source.dir}/helm-charts/charts/victoria-metrics-alert
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/victoriametrics-alert/config
