metadata:
  display-name: Argo CD Helm Chart
  short-description: Argo CD is a declarative continuous delivery tool for Kubernetes
  featured: false
  home-url: https://argo-cd.readthedocs.io/en/stable/
  categories:
    - integration-and-delivery
