image:
  registry: ${kube-state-metrics.registry}
  repository: ${kube-state-metrics.repository}
  tag: ${kube-state-metrics.tag}@${kube-state-metrics.digest}

kubeRBACProxy:
  image:
    registry: ${kube-rbac-proxy.registry}
    repository: ${kube-rbac-proxy.repository}
    tag: ${kube-rbac-proxy.tag}@${kube-rbac-proxy.digest}
