metadata:
  display-name: External Secrets Operator Helm chart
  short-description: External Secrets Operator is a Kubernetes operator that integrates external secret management systems like AWS Secrets Manager, HashiCorp Vault, Google Secrets Manager, Azure Key Vault, IBM Cloud Secrets Manager, Akeyless, CyberArk Secrets Manager, Pulumi ESC and many more
  featured: false
  home-url: https://github.com/external-secrets/external-secrets
  categories:
    - api-management
    - security
