metadata:
  display-name: Argo Rollouts Helm Chart
  short-description: Argo Rollouts is a Kubernetes controller and set of CRDs which provide advanced deployment capabilities
  featured: false
  home-url: https://argoproj.github.io/argo-rollouts/
  categories:
    - integration-and-delivery
