metadata:
  display-name: Helm
  short-description: Helm is the package manager for Kubernetes that helps you manage Kubernetes applications.
  featured: false
  home-url: https://helm.sh/
  categories:
    - developer-tools
