# syntax=dhi.io/build:2-debian13

name: Prometheus Operator Admission Webhook 0.x (dev)
image: dhi.io/prometheus-operator-admission-webhook
variant: dev
tags:
  - 0-dev
  - 0.89-dev
  - 0.89.0-dev
  - 0-debian13-dev
  - 0.89-debian13-dev
  - 0.89.0-debian13-dev
platforms:
  - linux/amd64
  - linux/arm64
dates: {}
vars:
  BASE_DIGEST: sha256:74fc43fa240887b8159970e434244039aab0c6efaaa9cf044004cdc22aa2a34d
  BASE_TAG: 20250419-debian13
  COMMIT_SHA: e13fb157486c9957c11a88fca97bf1a758a915c8
  GOLANG_REFERENCE: dhi/golang:1.26.0-debian13-dev@sha256:7c7ee6a2db0fa9a332ba1c96f2cc11b53dc7535a899ce66e45391db4dfa26350
  SEMVER_MAJOR_MINOR_VERSION: "0.89"
  SEMVER_MAJOR_VERSION: "0"
  SEMVER_VERSION: 0.89.0
  VERSION: 0.89.0
contents:
  packages:
    - '!base-files'
    - '!gawk'
    - '!libelogind0'
    - '!original-awk'
    - apt
    - bash
    - ca-certificates
    - coreutils
    - diffutils
    - dpkg
    - findutils
    - grep
    - libc-bin
    - mawk
    - perl-base
    - sed
    - util-linux
  builds:
    - name: prometheus-operator-admission-webhook
      uses: dhi.io/golang:1.26.0-debian13-dev@sha256:7c7ee6a2db0fa9a332ba1c96f2cc11b53dc7535a899ce66e45391db4dfa26350
      caches:
        - path: /go/pkg/mod
      contents:
        files:
          - url: git+https://github.com/prometheus-operator/prometheus-operator.git#v0.89.0
            checksum: e13fb157486c9957c11a88fca97bf1a758a915c8
            path: /go/src/github.com/prometheus-operator/prometheus-operator
            spdx:
              name: prometheus-operator
              version: 0.89.0
              packages:
                - name: prometheus-operator
                  purl: pkg:golang/github.com/prometheus-operator/prometheus-operator@0.89.0
                  license: Apache-2.0
            uid: 0
            gid: 0
      pipeline:
        - name: update go dependencies
          uses: go/bump@v1
          work-dir: /go/src/github.com/prometheus-operator/prometheus-operator
          caches:
            - path: /go/pkg/mod
          with:
            deps: []
            download: true
        - name: build
          uses: go/build@v1
          work-dir: /go/src/github.com/prometheus-operator/prometheus-operator
          with:
            ldflags:
              - -X github.com/prometheus/common/version.Version=0.89.0
              - -X github.com/prometheus/common/version.Revision=e13fb157486c9957c11a88fca97bf1a758a915c8
              - -X github.com/prometheus/common/version.Branch=dhi
              - -X github.com/prometheus/common/version.BuildUser=dhi
              - -X github.com/prometheus/common/version.BuildDate=$(date -u -d @${SOURCE_DATE_EPOCH} +'%F-%T')
            output: ${target.dir}/usr/local/bin/admission-webhook
            packages: ./cmd/admission-webhook/
      outputs:
        - source: ${target.dir}/usr/local/bin/admission-webhook
          target: /usr/local/bin/admission-webhook
          uid: 0
          gid: 0
        - source: /opt/docker/sbom/prometheus-operator
          target: /opt/docker/sbom/prometheus-operator
          uid: 0
          gid: 0
  artifacts:
    - name: dhi.io/static:20250419-debian13@sha256:74fc43fa240887b8159970e434244039aab0c6efaaa9cf044004cdc22aa2a34d
      includes:
        - bin
        - etc
        - home
        - lib
        - lib64
        - opt
        - sbin
        - tmp
        - usr
        - var
      excludes:
        - etc/group
        - etc/os-release
        - etc/passwd
        - var/lib/dpkg/status
      uid: 0
      gid: 0
accounts:
  root: true
  run-as: root
  users:
    - name: nonroot
      uid: 65532
      gid: 65532
    - name: _apt
      uid: 42
      gid: 65532
  groups:
    - name: nonroot
      gid: 65532
      members:
        - nonroot
os-release:
  name: Docker Hardened Images (Debian)
  id: debian
  version-id: "13"
  version-codename: trixie
  pretty-name: Docker Hardened Images/Debian GNU/Linux 13 (trixie)
  home-url: https://docker.com/products/hardened-images/
  bug-report-url: https://docker.com/support/
environment:
  DEBIAN_FRONTEND: noninteractive
annotations:
  org.opencontainers.image.description: A minimal Prometheus Operator Admission Webhook image
  org.opencontainers.image.licenses: Apache-2.0
entrypoint:
  - /usr/local/bin/admission-webhook
ports:
  - 8443/tcp
