# syntax=dhi.io/build:2-helm3

name: Velero Helm chart 11.x
image: dhi.io/velero-chart
variant: helm
tags:
  - 11.3.2
platforms:
  - linux/amd64
vars:
  CHART_COMMIT_SHA: b07a5226f3e4b25b8d44ea2266dac680bf8b5c2a
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_REFERENCE: dhi/helm:3.20.0-debian13-dev@sha256:7069456b86d57f9f2efaf7561c7f78097c6a4382a6e3420d23680ce61a045f34
  KUBECTL_REFERENCE: dhi/kubectl:1.35.0-debian13-compat@sha256:e9ed7d7909f6515ded0abc38e25bfca55ad72abb78270f41b48441adff546e17
  SEMVER_MAJOR_MINOR_VERSION: "11.3"
  SEMVER_MAJOR_VERSION: "11"
  SEMVER_VERSION: 11.3.2
  VELERO_REFERENCE: dhi/velero:1.17.2-debian13@sha256:f88922c357a754c71d2364972dfcfdae1ff8a227f0e5eab13f7e8fca113d245c
  VERSION: 11.3.2
contents:
  builds:
    - name: velero
      uses: dhi.io/helm:3.20.0-debian13-dev@sha256:7069456b86d57f9f2efaf7561c7f78097c6a4382a6e3420d23680ce61a045f34
      contents:
        files:
          - url: git+https://github.com/vmware-tanzu/helm-charts.git#velero-11.3.2
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/velero
          with:
            chart:
              appRef: velero
              description: Docker Hardened Images Helm chart for Velero
              images:
                - name: velero
                  ref: dhi/velero:1.17.2-debian13@sha256:f88922c357a754c71d2364972dfcfdae1ff8a227f0e5eab13f7e8fca113d245c
                - name: kubectl
                  ref: dhi/kubectl:1.35.0-debian13-compat@sha256:e9ed7d7909f6515ded0abc38e25bfca55ad72abb78270f41b48441adff546e17
              name: velero-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/vmware-tanzu/helm-charts
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/velero
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            process-templates: true
            registry: dhi.io
        - name: update dependencies
          uses: helm/cmd@v1
          with:
            chart: ${source.dir}/helm-charts/charts/velero
            cmd: dependency update
        - name: lint
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/charts
          with:
            chart: velero
            cmd: lint .
        - name: package
          uses: helm/package@v1
          with:
            chart: ${source.dir}/helm-charts/charts/velero
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/velero/config
