# syntax=dhi.io/build:2-helm3

name: Prometheus NATS Exporter Helm chart 2.x
image: dhi.io/prometheus-nats-exporter-chart
variant: helm
tags:
  - 2.22.0
platforms:
  - linux/amd64
vars:
  CHART_COMMIT_SHA: e383011a042d4abf70b0163a1fa95589d57f1298
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_REFERENCE: dhi/helm:3.20.0-debian13-dev@sha256:73af12ec3112d328c39a579a6b5a20d2667e69ee08be6644dce079721b4bce9c
  PROMETHEUS_NATS_EXPORTER_REFERENCE: dhi/prometheus-nats-exporter:0.19.1-debian13@sha256:b92bbb0b368279dafde6b0f58d55c57916637a81bb2f9fa8ac51f01778ab2ccb
  SEMVER_MAJOR_MINOR_VERSION: "2.22"
  SEMVER_MAJOR_VERSION: "2"
  SEMVER_VERSION: 2.22.0
  VERSION: 2.22.0
contents:
  builds:
    - name: prometheus-nats-exporter-chart
      uses: dhi.io/helm:3.20.0-debian13-dev@sha256:73af12ec3112d328c39a579a6b5a20d2667e69ee08be6644dce079721b4bce9c
      contents:
        files:
          - url: git+https://github.com/prometheus-community/helm-charts.git#prometheus-nats-exporter-2.22.0
            checksum: e383011a042d4abf70b0163a1fa95589d57f1298
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/prometheus-nats-exporter
          with:
            chart:
              appRef: prometheus-nats-exporter
              description: Docker Hardened Images Helm chart for Prometheus NATS Exporter
              images:
                - name: prometheus-nats-exporter
                  ref: dhi/prometheus-nats-exporter:0.19.1-debian13@sha256:b92bbb0b368279dafde6b0f58d55c57916637a81bb2f9fa8ac51f01778ab2ccb
              name: prometheus-nats-exporter-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/prometheus-community/helm-charts
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/prometheus-nats-exporter
          with:
            cmd: patch
            debug: true
            patches:
              from: ${source.dir}/config
            process-templates: true
            registry: dhi.io
        - name: update dependencies
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/charts
          privileged: true
          with:
            chart: prometheus-nats-exporter
            cmd: dependency update
        - name: lint
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/charts
          with:
            chart: prometheus-nats-exporter
            cmd: lint .
        - name: package
          uses: helm/package@v1
          work-dir: ${source.dir}/helm-charts/charts
          with:
            chart: prometheus-nats-exporter
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/prometheus-nats-exporter/config
