# syntax=dhi.io/build:2-helm3

name: Strimzi Kafka Operator Helm chart 0.x
image: dhi.io/strimzi-kafka-operator-chart
variant: helm
tags:
  - 0.1.1
platforms:
  - linux/amd64
vars:
  CHART_COMMIT_SHA: 825447910afa6e2db8f2897c4ada35dba9dcfa2a
  CHART_VERSION: 0.1.1
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_REFERENCE: dhi/helm:3.20.0-debian13-dev@sha256:73af12ec3112d328c39a579a6b5a20d2667e69ee08be6644dce079721b4bce9c
  SEMVER_MAJOR_MINOR_VERSION: "0.50"
  SEMVER_MAJOR_VERSION: "0"
  SEMVER_VERSION: 0.50.0
  STRIMZI_KAFKA_REFERENCE: dhi/strimzi-kafka:0.50.0-debian13-kafka-4.1.1@sha256:65068d478a1a8e2424fe80c916296b0ef24f59daeff153d43987d03cb57bb337
  STRIMZI_OPERATOR_REFERENCE: dhi/strimzi-operator:0.50.0-debian13@sha256:1c6605c2e39bb770f042d8cdac2ef07d4bd7597d3a12ab4b63568be4d5efff6b
  VERSION: 0.50.0
contents:
  builds:
    - name: strimzi-kafka-operator
      uses: dhi.io/helm:3.20.0-debian13-dev@sha256:73af12ec3112d328c39a579a6b5a20d2667e69ee08be6644dce079721b4bce9c
      contents:
        packages:
          - bash
          - build-essential
          - coreutils
          - grep
          - libc-bin
          - sed
        files:
          - url: git+https://github.com/strimzi/strimzi-kafka-operator.git#0.50.0
            checksum: 825447910afa6e2db8f2897c4ada35dba9dcfa2a
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/helm-charts/helm3/strimzi-kafka-operator
          with:
            chart:
              appRef: strimzi-operator
              description: Docker Hardened Images Helm chart for Strimzi Kafka Operator
              images:
                - name: strimzi-operator
                  ref: dhi/strimzi-operator:0.50.0-debian13@sha256:1c6605c2e39bb770f042d8cdac2ef07d4bd7597d3a12ab4b63568be4d5efff6b
                - name: strimzi-kafka
                  ref: dhi/strimzi-kafka:0.50.0-debian13-kafka-4.1.1@sha256:65068d478a1a8e2424fe80c916296b0ef24f59daeff153d43987d03cb57bb337
              name: strimzi-kafka-operator-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/strimzi/strimzi-kafka-operator
              version: 0.1.1
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/helm-charts/helm3/strimzi-kafka-operator
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: lint
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/helm-charts/helm3
          with:
            chart: strimzi-kafka-operator
            cmd: lint .
        - name: package
          uses: helm/package@v1
          work-dir: ${source.dir}/helm-charts/helm-charts/helm3
          with:
            chart: strimzi-kafka-operator
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/strimzi-kafka-operator/config
