# syntax=dhi.io/build:2-helm3

name: Strimzi Kafka Operator Helm chart 0.x
image: dhi.io/strimzi-kafka-operator-chart
variant: helm
tags:
  - 0.1.1
platforms:
  - linux/amd64
vars:
  CHART_COMMIT_SHA: d86dfbf4d1adf8f475e1c98cfbaf63e7b32f71c5
  CHART_VERSION: 0.1.1
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_REFERENCE: dhi/helm:3.20.0-debian13-dev@sha256:7069456b86d57f9f2efaf7561c7f78097c6a4382a6e3420d23680ce61a045f34
  SEMVER_MAJOR_MINOR_VERSION: "0.50"
  SEMVER_MAJOR_VERSION: "0"
  SEMVER_VERSION: 0.50.1
  STRIMZI_KAFKA_REFERENCE: dhi/strimzi-kafka:0.50.1-debian13-kafka-4.1.1@sha256:87a1f0096f8a894551042994e51dc93dc0d7161eb1c16d075e8d2e3a0fba9324
  STRIMZI_OPERATOR_REFERENCE: dhi/strimzi-operator:0.50.1-debian13@sha256:3e32ba88a2868d5b3e83faf1e67a3a56e34c9b77beb6fefafef665d28320f0b8
  VERSION: 0.50.1
contents:
  builds:
    - name: strimzi-kafka-operator
      uses: dhi.io/helm:3.20.0-debian13-dev@sha256:7069456b86d57f9f2efaf7561c7f78097c6a4382a6e3420d23680ce61a045f34
      contents:
        packages:
          - bash
          - build-essential
          - coreutils
          - grep
          - libc-bin
          - sed
        files:
          - url: git+https://github.com/strimzi/strimzi-kafka-operator.git#0.50.1
            checksum: d86dfbf4d1adf8f475e1c98cfbaf63e7b32f71c5
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/helm-charts/helm3/strimzi-kafka-operator
          with:
            chart:
              appRef: strimzi-operator
              description: Docker Hardened Images Helm chart for Strimzi Kafka Operator
              images:
                - name: strimzi-operator
                  ref: dhi/strimzi-operator:0.50.1-debian13@sha256:3e32ba88a2868d5b3e83faf1e67a3a56e34c9b77beb6fefafef665d28320f0b8
                - name: strimzi-kafka
                  ref: dhi/strimzi-kafka:0.50.1-debian13-kafka-4.1.1@sha256:87a1f0096f8a894551042994e51dc93dc0d7161eb1c16d075e8d2e3a0fba9324
              name: strimzi-kafka-operator-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/strimzi/strimzi-kafka-operator
              version: 0.1.1
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/helm-charts/helm3/strimzi-kafka-operator
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: lint
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/helm-charts/helm3
          with:
            chart: strimzi-kafka-operator
            cmd: lint .
        - name: package
          uses: helm/package@v1
          work-dir: ${source.dir}/helm-charts/helm-charts/helm3
          with:
            chart: strimzi-kafka-operator
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/strimzi-kafka-operator/config
