metadata:
  display-name: Grafana Rollout Operator Helm chart
  short-description: A Kubernetes operator for coordinating the rollout of Grafana pods between different StatefulSets.
  featured: false
  home-url: https://github.com/grafana/rollout-operator
  categories:
    - monitoring-and-observability
