vmselect:
  image:
    registry: ${victoriametrics-vmselect.registry}
    repository: ${victoriametrics-vmselect.repository}
    tag: ${victoriametrics-vmselect.tag}@${victoriametrics-vmselect.digest}
  podSecurityContext:
    enabled: true
    fsGroup: 65532
  securityContext:
    enabled: true
    runAsNonRoot: true
    runAsUser: 65532
    runAsGroup: 65532

vmstorage:
  image:
    registry: ${victoriametrics-vmstorage.registry}
    repository: ${victoriametrics-vmstorage.repository}
    tag: ${victoriametrics-vmstorage.tag}@${victoriametrics-vmstorage.digest}
  podSecurityContext:
    enabled: true
    fsGroup: 65532
  securityContext:
    enabled: true
    runAsNonRoot: true
    runAsUser: 65532
    runAsGroup: 65532

vminsert:
  image:
    registry: ${victoriametrics-vminsert.registry}
    repository: ${victoriametrics-vminsert.repository}
    tag: ${victoriametrics-vminsert.tag}@${victoriametrics-vminsert.digest}
  podSecurityContext:
    enabled: true
    fsGroup: 65532
  securityContext:
    enabled: true
    runAsNonRoot: true
    runAsUser: 65532
    runAsGroup: 65532

vmauth:
  image:
    registry: ${victoriametrics-vmauth.registry}
    repository: ${victoriametrics-vmauth.repository}
    tag: ${victoriametrics-vmauth.tag}@${victoriametrics-vmauth.digest}
  podSecurityContext:
    enabled: true
    fsGroup: 65532
  securityContext:
    enabled: true
    runAsNonRoot: true
    runAsUser: 65532
    runAsGroup: 65532
