# syntax=dhi.io/build:2-helm3

name: Clickhouse Operator Helm chart 0.x
image: dhi.io/clickhouse-operator-chart
variant: helm
tags:
  - 0.25.6
platforms:
  - linux/amd64
vars:
  CHART_COMMIT_SHA: 8d7dc3f2c0f6ef2e4e6be99792dd44cbefeb424c
  CLICKHOUSE_METRICS_EXPORTER_REFERENCE: dhi/clickhouse-metrics-exporter:0.25.6-debian13@sha256:338b2c1e0b9c99b1f044178220b96245d7fe3c33e73d1044a3327d2068493da9
  CLICKHOUSE_OPERATOR_IMAGE_TAG: 0.25.5
  CLICKHOUSE_OPERATOR_REFERENCE: dhi/clickhouse-operator:0.25.6-debian13@sha256:d45646c22dbaf93c003fcc81b712089654f0f561b6b993d40d865d5089dfb567
  CLICKHOUSE_SERVER_REFERENCE: dhi/clickhouse-server:25.8.15-debian13@sha256:862727fca537a0a1a7da266d637d5b58ae614f4b482154a9ec8de2654c9184ce
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_REFERENCE: dhi/helm:3.19.5-debian13-dev@sha256:9fa0f8ba70052f17df5a7a3469c2e306d18b5f934f3439ce781c9dd5a2f6b96a
  KUBECTL_REFERENCE: dhi/kubectl:1.34.3-alpine3.22-dev@sha256:0459b7b67ab31a30e497ad651a8d00963f836d73d9e33f1cc6b1c6edb7a0a2cd
  SEMVER_MAJOR_MINOR_VERSION: "0.25"
  SEMVER_MAJOR_VERSION: "0"
  SEMVER_VERSION: 0.25.6
  VERSION: 0.25.6
contents:
  builds:
    - name: clickhouse-operator-chart
      uses: dhi.io/helm:3.19.5-debian13-dev@sha256:9fa0f8ba70052f17df5a7a3469c2e306d18b5f934f3439ce781c9dd5a2f6b96a
      contents:
        files:
          - url: git+https://github.com/Altinity/clickhouse-operator.git#release-0.25.6
            checksum: 8d7dc3f2c0f6ef2e4e6be99792dd44cbefeb424c
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/deploy/helm/clickhouse-operator
          with:
            chart:
              appRef: clickhouse-operator
              description: Docker Hardened Images Helm chart for ClickHouse Operator
              images:
                - name: clickhouse-operator
                  ref: dhi/clickhouse-operator:0.25.6-debian13@sha256:d45646c22dbaf93c003fcc81b712089654f0f561b6b993d40d865d5089dfb567
                - name: clickhouse-metrics-exporter
                  ref: dhi/clickhouse-metrics-exporter:0.25.6-debian13@sha256:338b2c1e0b9c99b1f044178220b96245d7fe3c33e73d1044a3327d2068493da9
                - name: clickhouse-server
                  ref: dhi/clickhouse-server:25.8.15-debian13@sha256:862727fca537a0a1a7da266d637d5b58ae614f4b482154a9ec8de2654c9184ce
                - name: kubectl
                  ref: dhi/kubectl:1.34.3-alpine3.22-dev@sha256:0459b7b67ab31a30e497ad651a8d00963f836d73d9e33f1cc6b1c6edb7a0a2cd
              name: clickhouse-operator-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/cert-manager/cert-manager
            cmd: prepare
            registry: dhi.io
        - name: update values
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/deploy/helm/clickhouse-operator
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: update dependencies
          uses: helm/cmd@v1
          with:
            chart: ${source.dir}/helm-charts/deploy/helm/clickhouse-operator
            cmd: dependency update
        - name: lint
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/deploy/helm
          with:
            chart: clickhouse-operator
            cmd: lint .
        - name: package
          uses: helm/package@v1
          with:
            chart: ${source.dir}/helm-charts/deploy/helm/clickhouse-operator
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/clickhouse-operator/config
