metadata:
  display-name: Grafana
  short-description: Query, visualize, alert on, and explore your metrics, logs, and traces wherever they are stored.
  featured: false
  home-url: https://grafana.com/docs/grafana/latest/
  categories:
    - developer-tools
    - monitoring-and-observability
