server:
  image:
    repository: ${vault.repository}
    tag: ${vault.tag}
  statefulSet:
    securityContext:
      container:
        capabilities:
          add:
            - IPC_LOCK

injector:
  agentImage:
    repository: ${vault.repository}
    tag: ${vault.tag}@${vault.digest}
  image:
    repository: ${vault-k8s.repository}
    tag: ${vault-k8s.tag}@${vault-k8s.digest}

csi:
  image:
    repository: ${vault-csi-provider.repository}
    tag: ${vault-csi-provider.tag}@${vault-csi-provider.digest}
  agent:
    image:
      repository: ${vault.repository}
      tag: ${vault.tag}@${vault.digest}
