# syntax=dhi.io/build:2-helm3

name: External Secrets Operator Helm chart 1.x
image: dhi.io/external-secrets-chart
variant: helm
tags:
  - 1.3.2
platforms:
  - linux/amd64
vars:
  CHART_COMMIT_SHA: a8fd8f6cc19b70bc5c828d5bf4c2ec8488360040
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  EXTERNAL_SECRETS_REFERENCE: dhi/external-secrets:1.3.2-debian13@sha256:95fa0d13dfb47f53463bde9fcf5b33b9c5d78f8535ff015c0aea0e731ab86447
  HELM_REFERENCE: dhi/helm:3.20.0-debian13-dev@sha256:7069456b86d57f9f2efaf7561c7f78097c6a4382a6e3420d23680ce61a045f34
  SEMVER_MAJOR_MINOR_VERSION: "1.3"
  SEMVER_MAJOR_VERSION: "1"
  SEMVER_VERSION: 1.3.2
  VERSION: 1.3.2
contents:
  builds:
    - name: external-secrets
      uses: dhi.io/helm:3.20.0-debian13-dev@sha256:7069456b86d57f9f2efaf7561c7f78097c6a4382a6e3420d23680ce61a045f34
      contents:
        packages:
          - bash
          - build-essential
          - coreutils
          - grep
          - libc-bin
          - sed
        files:
          - url: git+https://github.com/external-secrets/external-secrets.git#helm-chart-1.3.2
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/deploy/charts/external-secrets
          with:
            chart:
              appRef: external-secrets
              description: Docker Hardened Images Helm chart for External Secrets Operator
              images:
                - name: external-secrets
                  ref: dhi/external-secrets:1.3.2-debian13@sha256:95fa0d13dfb47f53463bde9fcf5b33b9c5d78f8535ff015c0aea0e731ab86447
              name: external-secrets-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/external-secrets/external-secrets
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/deploy/charts/external-secrets
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: blank 3rd party images
          work-dir: ${source.dir}/helm-charts/deploy/charts/external-secrets
          runs: |
            set -eux -o pipefail

            yq eval 'del(.dependencies)' Chart.yaml \
              | awk '{print} END{print ""}' > tmp && mv tmp Chart.yaml
        - name: update dependencies
          uses: helm/cmd@v1
          with:
            chart: ${source.dir}/helm-charts/deploy/charts/external-secrets
            cmd: dependency update
        - name: generate CRDs
          runs: |
            set -eux -o pipefail

            cd ${source.dir}/helm-charts

            make helm.generate
        - name: lint
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/deploy/charts
          with:
            chart: external-secrets
            cmd: lint .
        - name: package
          uses: helm/package@v1
          with:
            chart: ${source.dir}/helm-charts/deploy/charts/external-secrets
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/external-secrets/config
