metadata:
  display-name: HAProxy Helm chart
  short-description: The Reliable, High Performance TCP/HTTP Load Balancer
  featured: true
  home-url: https://www.haproxy.org/
  categories:
    - networking
