image:
  keda:
    registry: ${keda.registry}
    repository: ${keda.repository}
    tag: ${keda.tag}@${keda.digest}
  metricsApiServer:
    registry: ${keda-metrics-apiserver.registry}
    repository: ${keda-metrics-apiserver.repository}
    tag: ${keda-metrics-apiserver.tag}@${keda-metrics-apiserver.digest}
  webhooks:
    registry: ${keda-admission-webhooks.registry}
    repository: ${keda-admission-webhooks.repository}
    tag: ${keda-admission-webhooks.tag}@${keda-admission-webhooks.digest}

# Upstream already sets run as non-root on all containers
