image:
  repository: ${velero.registry}/${velero.repository}
  tag: ${velero.tag}@${velero.digest}
podSecurityContext:
  fsGroup: 65532
containerSecurityContext:
  runAsNonRoot: true
  runAsUser: 65532
  runAsGroup: 65532
  allowPrivilegeEscalation: false
  capabilities:
    drop: ["ALL"]
    add: []
  readOnlyRootFilesystem: true
upgradeCRDsJob:
  shellCmd: velero
  updateCmd: --crds-only
kubectl:
  image:
    repository: ${kubectl.registry}/${kubectl.repository}
    tag: ${kubectl.tag}@${kubectl.digest}
  podSecurityContext:
    fsGroup: 65532
  containerSecurityContext:
    runAsNonRoot: true
    runAsUser: 65532
    runAsGroup: 65532
    allowPrivilegeEscalation: false
    capabilities:
      drop: ["ALL"]
      add: []
    readOnlyRootFilesystem: true

nodeAgent:
  podSecurityContext:
    fsGroup: 65532
  containerSecurityContext:
    runAsNonRoot: true
    runAsUser: 65532
    runAsGroup: 65532
    allowPrivilegeEscalation: false
    capabilities:
      drop: ["ALL"]
      add: []
    readOnlyRootFilesystem: true
