image:
  registry: ${grafana.registry}
  repository: ${grafana.repository}
  tag: ${grafana.tag}@${grafana.digest}

testFramework:
  image:
    registry: ${bats.registry}
    repository: ${bats.repository}
    tag: ${bats.tag}@${bats.digest}

downloadDashboardsImage:
  registry: ${curl.registry}
  repository: ${curl.repository}
  tag: ${curl.tag}@${curl.digest}

initChownData:
  image:
    registry: ${busybox.registry}
    repository: ${busybox.repository}
    tag: ${busybox.tag}@${busybox.digest}

sidecar:
  image:
    registry: ${k8s-sidecar.registry}
    repository: ${k8s-sidecar.repository}
    tag: ${k8s-sidecar.tag}@${k8s-sidecar.digest}

imageRenderer:
  image:
    registry: ${grafana-image-renderer.registry}
    repository: ${grafana-image-renderer.repository}
    tag: ${grafana-image-renderer.tag}@${grafana-image-renderer.digest}

securityContext:
  runAsNonRoot: true
  runAsUser: 65532
  runAsGroup: 65532
  fsGroup: 65532
