image:
  repository: ${stakater-reloader.registry}/${stakater-reloader.repository}
  tag: ${stakater-reloader.tag}@${stakater-reloader.digest}
reloader:
  deployment:
    securityContext:
      runAsUser: 65532
      runAsGroup: 65532
      runAsNonRoot: true
