metadata:
  display-name: KEDA Helm chart
  short-description: KEDA is an open-source project that enables event-driven autoscaling for Kubernetes workloads.
  featured: false
  home-url: https://github.com/kedacore/charts/tree/main/keda
  categories:
    - developer-tools
    - integration-and-delivery
