metadata:
  display-name: VictoriaMetrics Alerts Helm chart
  short-description: Executes a list of given MetricsQL expressions (rules) and sends alerts to Alert Manager
  featured: false
  home-url: https://victoriametrics.com
  categories:
    - monitoring-and-observability
