image:
    repository: ${kubernetes-cluster-autoscaler.registry}/${kubernetes-cluster-autoscaler.repository}
    tag: ${kubernetes-cluster-autoscaler.tag}@${kubernetes-cluster-autoscaler.digest}
securityContext:
  runAsNonRoot: true
  runAsUser: 65532
  runAsGroup: 65532
