image:
  registry: ${blackbox-exporter.registry}
  repository: ${blackbox-exporter.repository}
  tag: ${blackbox-exporter.tag}
  digest: ${blackbox-exporter.digest}
configReloader:
  image:
    registry: ${prometheus-config-reloader.registry}
    repository: ${prometheus-config-reloader.repository}
    tag: ${prometheus-config-reloader.tag}
    digest: ${prometheus-config-reloader.digest}

podSecurityContext:
  fsGroup: 65532

securityContext:
  runAsNonRoot: true
  runAsUser: 65532
  runAsGroup: 65532
