metadata:
  display-name: Valkey Helm chart
  short-description: Valkey is a high-performance key/value datastore that supports a variety of workloads such as caching, message queues, and can act as a primary database.
  featured: false
  home-url: https://valkey.io
  categories:
    - databases-and-storage
    - message-queues
