# syntax=dhi.io/build:2-helm3

name: Goldilocks Helm chart 10.x
image: dhi.io/goldilocks-chart
variant: helm
tags:
  - 10.3.0
platforms:
  - linux/amd64
vars:
  CHART_COMMIT_SHA: 711b1723b2d1fa0ef9c63793c8f62d1d407bc469
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  FAIRWINDS_VPA_REFERENCE: dhi/fairwinds-vpa-chart:4.10.1@sha256:f488fc3e4238af51759beb6a65301424feb67b7836ac5d933a3e9f1f8ba807b2
  GOLDILOCKS_REFERENCE: dhi/goldilocks:4.14.10-debian13@sha256:b9480b7195af5776907fe14f2a7e3a3cab126410cc56a4e6a5f8d5dd551f6e2d
  HELM_REFERENCE: dhi/helm:3.20.0-debian13-dev@sha256:7069456b86d57f9f2efaf7561c7f78097c6a4382a6e3420d23680ce61a045f34
  METRICS_SERVER_REFERENCE: dhi/metrics-server-chart:3.13.0@sha256:723ee6f11fd997a5907738efceedb614b6e9ea0153aee46da04fce7577e8ce7e
  SEMVER_MAJOR_MINOR_VERSION: "10.3"
  SEMVER_MAJOR_VERSION: "10"
  SEMVER_VERSION: 10.3.0
  VERSION: 10.3.0
contents:
  builds:
    - name: goldilocks-chart
      uses: dhi.io/helm:3.20.0-debian13-dev@sha256:7069456b86d57f9f2efaf7561c7f78097c6a4382a6e3420d23680ce61a045f34
      contents:
        files:
          - url: git+https://github.com/FairwindsOps/charts.git#711b1723b2d1fa0ef9c63793c8f62d1d407bc469
            checksum: 711b1723b2d1fa0ef9c63793c8f62d1d407bc469
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/stable/goldilocks
          with:
            chart:
              appRef: goldilocks
              dependencies:
                - alias: metrics-server
                  condition: metrics-server.enabled
                  name: metrics-server
                  ref: dhi/metrics-server-chart:3.13.0@sha256:723ee6f11fd997a5907738efceedb614b6e9ea0153aee46da04fce7577e8ce7e
                - alias: vpa
                  condition: vpa.enabled
                  name: vpa
                  ref: dhi/fairwinds-vpa-chart:4.10.1@sha256:f488fc3e4238af51759beb6a65301424feb67b7836ac5d933a3e9f1f8ba807b2
              description: Docker Hardened Images Helm chart for Goldilocks
              images:
                - name: goldilocks
                  ref: dhi/goldilocks:4.14.10-debian13@sha256:b9480b7195af5776907fe14f2a7e3a3cab126410cc56a4e6a5f8d5dd551f6e2d
              name: goldilocks-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/FairwindsOps/charts
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/stable/goldilocks
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: helm login
          uses: helm/login@v1
          with:
            registry: dhi.io
        - name: update dependencies
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/stable
          privileged: true
          with:
            chart: goldilocks
            cmd: dependency update
        - name: lint
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/stable
          with:
            chart: goldilocks
            cmd: lint .
        - name: package
          uses: helm/package@v1
          work-dir: ${source.dir}/helm-charts/stable
          with:
            chart: goldilocks
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/goldilocks/config
