image:
  repository: ${external-secrets.registry}/${external-secrets.repository}
  tag: ${external-secrets.tag}@${external-secrets.digest}

webhook:
  image:
    repository: ${external-secrets.registry}/${external-secrets.repository}
    tag: ${external-secrets.tag}@${external-secrets.digest}

certController:
  image:
    repository: ${external-secrets.registry}/${external-secrets.repository}
    tag: ${external-secrets.tag}@${external-secrets.digest}
