metadata:
  display-name: Prometheus Blackbox Exporter Helm chart
  short-description: Prometheus exporter for probing network endpoints via HTTP, HTTPS, DNS, TCP, ICMP, and gRPC.
  featured: false
  home-url: https://github.com/prometheus-community/helm-charts/tree/main/charts/prometheus-blackbox-exporter
  categories:
    - monitoring-and-observability
