metadata:
  display-name: Grafana Operator Helm chart
  short-description: A Kubernetes operator for managing Grafana instances, dashboards, and datasources declaratively.
  featured: false
  home-url: https://github.com/grafana/grafana-operator/tree/master/deploy/helm/grafana-operator
  categories:
    - monitoring-and-observability
