global:
  dockerRegistry: ${opensearch.registry}

image:
  repository: ${opensearch.repository}
  tag: ${opensearch.tag}

persistence:
  image: ${busybox.repository}
  imageTag: ${busybox.tag}@${busybox.digest}
