metadata:
  display-name: Prometheus Operator Admission Webhook
  short-description: Kubernetes webhook for managing Prometheus.
  featured: false
  home-url: https://prometheus-operator.dev/
  categories:
    - monitoring-and-observability
