# syntax=dhi.io/build:2-helm3

name: Kube State Metrics Helm chart 7.x
image: dhi.io/kube-state-metrics-chart
variant: helm
tags:
  - 7.2.0
platforms:
  - linux/amd64
vars:
  CHART_COMMIT_SHA: 6ebd4382528da17e8f9f1e3e8c6d054c02fc1eda
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_REFERENCE: dhi/helm:3.20.0-debian13-dev@sha256:7069456b86d57f9f2efaf7561c7f78097c6a4382a6e3420d23680ce61a045f34
  KUBE_RBAC_PROXY_REFERENCE: dhi/kube-rbac-proxy:0.21.0-debian13@sha256:fad548b08be8b31acda60fec1459daa94393baa04982d9acb1d04fc77e9f0b27
  KUBE_STATE_METRICS_REFERENCE: dhi/kube-state-metrics:2.18.0-debian13@sha256:f953dc5ef315fa1c3a06aac7edaf65f9a015d78ed3b871271ab7c3f27ae553c8
  SEMVER_MAJOR_MINOR_VERSION: "7.2"
  SEMVER_MAJOR_VERSION: "7"
  SEMVER_VERSION: 7.2.0
  VERSION: 7.2.0
contents:
  builds:
    - name: kube-state-metrics-chart
      uses: dhi.io/helm:3.20.0-debian13-dev@sha256:7069456b86d57f9f2efaf7561c7f78097c6a4382a6e3420d23680ce61a045f34
      contents:
        files:
          - url: git+https://github.com/prometheus-community/helm-charts.git#kube-state-metrics-7.2.0
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/kube-state-metrics
          with:
            chart:
              appRef: kube-state-metrics
              description: Docker Hardened Images Helm chart for Kube State Metrics
              images:
                - name: kube-state-metrics
                  ref: dhi/kube-state-metrics:2.18.0-debian13@sha256:f953dc5ef315fa1c3a06aac7edaf65f9a015d78ed3b871271ab7c3f27ae553c8
                - name: kube-rbac-proxy
                  ref: dhi/kube-rbac-proxy:0.21.0-debian13@sha256:fad548b08be8b31acda60fec1459daa94393baa04982d9acb1d04fc77e9f0b27
              name: kube-state-metrics-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/prometheus-community/helm-charts
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/kube-state-metrics
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: update dependencies
          uses: helm/cmd@v1
          privileged: true
          with:
            chart: ${source.dir}/helm-charts/charts/kube-state-metrics
            cmd: dependency update
        - name: lint
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/charts
          with:
            chart: kube-state-metrics
            cmd: lint .
        - name: package
          uses: helm/package@v1
          with:
            chart: ${source.dir}/helm-charts/charts/kube-state-metrics
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/kube-state-metrics/config
