metadata:
  display-name: Prometheus AlertManager Helm chart
  short-description: Alertmanager deduplicates, groups, and routes alerts from Prometheus to notification receivers and supports silences, inhibition and HA clustering.
  featured: false
  home-url: https://github.com/prometheus/alertmanager
  categories:
    - monitoring-and-observability
