# syntax=dhi.io/build:2-alpine3.23

image: dhi.io/pkg-helm
variant: runtime
tags:
  - 4.1.1-alpine3.23
  - 4.1.1-r0-alpine3.23
platforms:
  - linux/amd64
  - linux/arm64
vars:
  COMMIT_SHA: 5caf0044d4ef3d62a955440272999e139aafbbed
  PACKAGE_NAME: helm
  REL: "0"
  SEMVER_MAJOR_MINOR_VERSION: "4.1"
  SEMVER_MAJOR_VERSION: "4"
  SEMVER_VERSION: 4.1.1
  VERSION: 4.1.1
contents:
  repositories:
    - https://dhi.io/apk/alpine/v3.23/main
    - https://dl-cdn.alpinelinux.org/alpine/v3.23/main
    - https://dl-cdn.alpinelinux.org/alpine/v3.23/community
  keyring:
    - https://dhi.io/keyring/dhi-apk@docker-0F81AD7700D99184.rsa.pub
  packages:
    - alpine-baselayout-data
  builds:
    - name: helm
      work-dir: /go/src/github.com/helm/helm
      contents:
        packages:
          - busybox
          - bash
          - golang-1.25
          - golang-1.25-oci-config
          - sed
        files:
          - url: git+https://github.com/helm/helm.git#v4.1.1
            checksum: 5caf0044d4ef3d62a955440272999e139aafbbed
            path: /go/src/github.com/helm/helm
            uid: 0
            gid: 0
      pipeline:
        - name: update go dependencies
          uses: go/bump@v1
          with:
            deps: []
            tidy: true
        - uses: go/hermetic@v1
        - name: build
          uses: go/build@v1
          environment:
            GOFLAGS: -buildvcs=false
          with:
            cgo_enabled: 0
            fips: false
            ldflags:
              - -X helm.sh/helm/v4/internal/version.version=4.1.1
              - -X helm.sh/helm/v4/internal/version.gitCommit=5caf0044d4ef3d62a955440272999e139aafbbed
              - -X helm.sh/helm/v4/internal/version.gitTreeState=clean
              - -X helm.sh/helm/v4/internal/version.metadata=
            output: ${target.dir}/usr/bin/helm
            packages: ./cmd/helm
        - name: build dev
          uses: go/build@v1
          environment:
            GOFLAGS: -buildvcs=false
          with:
            cgo_enabled: 0
            fips: false
            ldflags:
              - -X helm.sh/helm/v4/internal/version.version=4.1.1
              - -X helm.sh/helm/v4/internal/version.gitCommit=5caf0044d4ef3d62a955440272999e139aafbbed
              - -X helm.sh/helm/v4/internal/version.gitTreeState=clean
              - -X helm.sh/helm/v4/internal/version.metadata=
            output: ${target.dir}/usr/bin/helm-dev
            packages: ./cmd/helm
            strip: false
        - uses: sbom@v1
          with:
            prefix: helm-go
            source: ${target.dir}
        - uses: abuild/setup@v1
          work-dir: ${source.dir}/aports/helm
        - uses: abuild/apk@v1
          work-dir: ${source.dir}/aports/helm
          with:
            description: The Kubernetes Package Manager
            functions:
              dev: |
                pkgdesc="$pkgdesc (dev)"
                mkdir -p "$subpkgdir/usr/bin"
                mv "$pkgdir/usr/bin/helm-dev" "$subpkgdir/usr/bin/helm"
            license: Apache-2.0
            name: helm
            options: '!check !strip'
            rel: 0
            subpackages: $pkgname-dev
            url: https://github.com/helm/helm
            version: 4.1.1
        - uses: abuild/build@v1
          work-dir: ${source.dir}/aports/helm
        - uses: abuild/upload@v1
    - name: helm-fips
      work-dir: /go/src/github.com/helm/helm
      contents:
        packages:
          - busybox
          - bash
          - golang-1.25
          - golang-1.25-oci-config
          - sed
        files:
          - url: git+https://github.com/helm/helm.git#v4.1.1
            checksum: 5caf0044d4ef3d62a955440272999e139aafbbed
            path: /go/src/github.com/helm/helm
            uid: 0
            gid: 0
      pipeline:
        - name: update go dependencies
          uses: go/bump@v1
          with:
            deps: []
            tidy: true
        - uses: go/hermetic@v1
        - name: build
          uses: go/build@v1
          environment:
            GOFLAGS: -buildvcs=false
          with:
            cgo_enabled: 0
            fips: true
            ldflags:
              - -X helm.sh/helm/v4/internal/version.version=4.1.1
              - -X helm.sh/helm/v4/internal/version.gitCommit=5caf0044d4ef3d62a955440272999e139aafbbed
              - -X helm.sh/helm/v4/internal/version.gitTreeState=clean
              - -X helm.sh/helm/v4/internal/version.metadata=
            output: ${target.dir}/usr/bin/helm
            packages: ./cmd/helm
        - name: build dev
          uses: go/build@v1
          environment:
            GOFLAGS: -buildvcs=false
          with:
            cgo_enabled: 0
            fips: true
            ldflags:
              - -X helm.sh/helm/v4/internal/version.version=4.1.1
              - -X helm.sh/helm/v4/internal/version.gitCommit=5caf0044d4ef3d62a955440272999e139aafbbed
              - -X helm.sh/helm/v4/internal/version.gitTreeState=clean
              - -X helm.sh/helm/v4/internal/version.metadata=
            output: ${target.dir}/usr/bin/helm-dev
            packages: ./cmd/helm
            strip: false
        - uses: sbom@v1
          with:
            prefix: helm-fips-go
            source: ${target.dir}
        - uses: abuild/setup@v1
          work-dir: ${source.dir}/aports/helm-fips
        - uses: abuild/apk@v1
          work-dir: ${source.dir}/aports/helm-fips
          with:
            description: The Kubernetes Package Manager
            functions:
              dev: |
                pkgdesc="$pkgdesc (dev)"
                mkdir -p "$subpkgdir/usr/bin"
                mv "$pkgdir/usr/bin/helm-dev" "$subpkgdir/usr/bin/helm"
            license: Apache-2.0
            name: helm-fips
            options: '!check !strip'
            rel: 0
            subpackages: $pkgname-dev
            url: https://github.com/helm/helm
            version: 4.1.1
        - uses: abuild/build@v1
          work-dir: ${source.dir}/aports/helm-fips
        - uses: abuild/upload@v1
os-release:
  name: Docker Hardened Images (Alpine)
  id: alpine
  version-id: "3.23"
  pretty-name: Docker Hardened Images/Alpine Linux v3.23
  home-url: https://docker.com/products/hardened-images/
  bug-report-url: https://docker.com/support/
