# syntax=dhi.io/build:2-helm3

name: Kube Prometheus Stack Helm chart 82.x
image: dhi.io/kube-prometheus-stack-chart
variant: helm
tags:
  - 82.4.3
platforms:
  - linux/amd64
vars:
  ADMISSION_WEBHOOK_REFERENCE: dhi/prometheus-operator-admission-webhook:0.89.0-debian13@sha256:99031ce1d0ada33a38b96de5697ad69bc7d8be06969c50535ad0985fe2d49a9a
  ALERTMANAGER_REFERENCE: dhi/alertmanager:0.31.1-debian13@sha256:2bf707ab63d56f9b86964111a0aa0c44d84d5821c993343768ec429b47d62dda
  BUSYBOX_REFERENCE: dhi/busybox:1.37.0-debian13@sha256:ee1f963dd3d57a59ae3f99fca81b06d19d1bef7c8289ff84001e0c65f39a8464
  CHART_COMMIT_SHA: a9aa429f6b537d7420dec15fcddca6b4dd3031f3
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  GRAFANA_CHART_REFERENCE: dhi/grafana-chart:11.2.2@sha256:1987326bab1cf81180b5a865cd50268193588ce42c6cae0cd238eb277ff11394
  HELM_REFERENCE: dhi/helm:3.20.0-debian13-dev@sha256:7069456b86d57f9f2efaf7561c7f78097c6a4382a6e3420d23680ce61a045f34
  KUBE_STATE_METRICS_CHART_REFERENCE: dhi/kube-state-metrics-chart:7.2.0@sha256:a945a67eb43e9766e30102f89c0165250780818a7a6f12d50ca653040ef084c9
  KUBE_WEBHOOK_CERTGEN_REFERENCE: dhi/kube-webhook-certgen:1.7.8-debian13@sha256:e14d14bd71da5e868078db9fff414c78b9da40dd82589a322232636fa1dd05d1
  KUBECTL_REFERENCE: dhi/kubectl:1.35.0-debian13@sha256:c5cbc3a9101f0715d9511c9a722802d74c14697aec1336903a18a2b742b8fb13
  NODE_EXPORTER_CHART_REFERENCE: dhi/node-exporter-chart:4.52.0@sha256:4f2f0cc4145bbd6dd67449883521d1b08babd600458f7c47fca90f97a771c5f9
  PROMETHEUS_CONFIG_RELOADER_REFERENCE: dhi/prometheus-config-reloader:0.89.0-debian13@sha256:2d5cb7f61093b680ce65cd6b35ed16337c237f5ebc95b32b09cd9a91a0b1f995
  PROMETHEUS_OPERATOR_REFERENCE: dhi/prometheus-operator:0.89.0-debian13@sha256:2a4d5b1919666bfb94ebfa5f1f678e82a810339abb3fee8e538839102618dda0
  PROMETHEUS_REFERENCE: dhi/prometheus:3.10.0-debian13@sha256:53bdb9ac8260e32410feebf6dbc7b2fbcc274c75678f263e7a7607b314239aff
  SEMVER_MAJOR_MINOR_VERSION: "82.4"
  SEMVER_MAJOR_VERSION: "82"
  SEMVER_VERSION: 82.4.3
  THANOS_REFERENCE: dhi/thanos:0.41.0-debian13@sha256:683a214f32878cfd7be188c012bd8870ce7a38754188efbf944dafc2d8ab67a0
  VERSION: 82.4.3
contents:
  builds:
    - name: kube-prometheus-stack-chart
      uses: dhi.io/helm:3.20.0-debian13-dev@sha256:7069456b86d57f9f2efaf7561c7f78097c6a4382a6e3420d23680ce61a045f34
      contents:
        packages:
          - bash
          - build-essential
          - coreutils
          - grep
          - libc-bin
          - sed
        files:
          - url: git+https://github.com/prometheus-community/helm-charts.git#kube-prometheus-stack-82.4.3
            checksum: a9aa429f6b537d7420dec15fcddca6b4dd3031f3
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/kube-prometheus-stack
          with:
            chart:
              appRef: prometheus-operator
              dependencies:
                - condition: crds.enabled
                  keep: true
                  name: crds
                - alias: kube-state-metrics
                  condition: kubeStateMetrics.enabled
                  name: kube-state-metrics
                  ref: dhi/kube-state-metrics-chart:7.2.0@sha256:a945a67eb43e9766e30102f89c0165250780818a7a6f12d50ca653040ef084c9
                - alias: prometheus-node-exporter
                  condition: nodeExporter.enabled
                  name: node-exporter
                  ref: dhi/node-exporter-chart:4.52.0@sha256:4f2f0cc4145bbd6dd67449883521d1b08babd600458f7c47fca90f97a771c5f9
                - alias: grafana
                  condition: grafana.enabled
                  name: grafana
                  ref: dhi/grafana-chart:11.2.2@sha256:1987326bab1cf81180b5a865cd50268193588ce42c6cae0cd238eb277ff11394
              description: Docker Hardened Images Helm chart for Kube Prometheus Stack
              images:
                - name: busybox
                  ref: dhi/busybox:1.37.0-debian13@sha256:ee1f963dd3d57a59ae3f99fca81b06d19d1bef7c8289ff84001e0c65f39a8464
                - name: kubectl
                  ref: dhi/kubectl:1.35.0-debian13@sha256:c5cbc3a9101f0715d9511c9a722802d74c14697aec1336903a18a2b742b8fb13
                - name: alertmanager
                  ref: dhi/alertmanager:0.31.1-debian13@sha256:2bf707ab63d56f9b86964111a0aa0c44d84d5821c993343768ec429b47d62dda
                - name: prometheus-operator-admission-webhook
                  ref: dhi/prometheus-operator-admission-webhook:0.89.0-debian13@sha256:99031ce1d0ada33a38b96de5697ad69bc7d8be06969c50535ad0985fe2d49a9a
                - name: kube-webhook-certgen
                  ref: dhi/kube-webhook-certgen:1.7.8-debian13@sha256:e14d14bd71da5e868078db9fff414c78b9da40dd82589a322232636fa1dd05d1
                - name: prometheus-operator
                  ref: dhi/prometheus-operator:0.89.0-debian13@sha256:2a4d5b1919666bfb94ebfa5f1f678e82a810339abb3fee8e538839102618dda0
                - name: prometheus-config-reloader
                  ref: dhi/prometheus-config-reloader:0.89.0-debian13@sha256:2d5cb7f61093b680ce65cd6b35ed16337c237f5ebc95b32b09cd9a91a0b1f995
                - name: thanos
                  ref: dhi/thanos:0.41.0-debian13@sha256:683a214f32878cfd7be188c012bd8870ce7a38754188efbf944dafc2d8ab67a0
                - name: prometheus
                  ref: dhi/prometheus:3.10.0-debian13@sha256:53bdb9ac8260e32410feebf6dbc7b2fbcc274c75678f263e7a7607b314239aff
              name: kube-prometheus-stack-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/prometheus-community/helm-charts
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/kube-prometheus-stack
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: helm login
          uses: helm/login@v1
          with:
            registry: dhi.io
        - name: pull dependencies
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/charts
          privileged: true
          with:
            chart: kube-prometheus-stack
            cmd: dependency update
        - name: lint
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/charts
          with:
            chart: kube-prometheus-stack
            cmd: lint .
        - name: package
          uses: helm/package@v1
          work-dir: ${source.dir}/helm-charts/charts
          with:
            chart: kube-prometheus-stack
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/kube-prometheus-stack/config
