metadata:
  display-name: Cert-Manager Helm chart
  short-description: Cert-Manager is a TLS certificate management controller for Kubernetes.
  featured: false
  home-url: https://cert-manager.io/
  categories:
    - security
