image:
  repository: ${argocd-image-updater.registry}/${argocd-image-updater.repository}
  tag: ${argocd-image-updater.tag}@${argocd-image-updater.digest}

# No need for security context or pod security context overrides as the image is already hardened
