metadata:
  display-name: Velero Helm chart
  short-description: Velero is an open source tool to safely back up and restore, perform disaster recovery, and migrate Kubernetes cluster resources and persistent volumes.
  featured: false
  home-url: https://velero.io/docs/main/
  categories:
    - databases-and-storage
    - integration-and-delivery
