metadata:
  display-name: Argo CD Image Updater Helm chart
  short-description: A tool to automatically update container images of Kubernetes workloads managed by Argo CD.
  featured: false
  home-url: https://github.com/argoproj/argo-helm
  categories:
    - integration-and-delivery
