metadata:
  display-name: ClickHouse Operator Helm chart
  short-description: ClickHouse is the fastest and most resource efficient OSS database for real-time apps and analytics.
  featured: false
  home-url: https://clickhouse.com/
  categories:
    - databases-and-storage
