metadata:
  display-name: Sealed Secrets Controller Helm chart
  short-description: Sealed Secrets is a Kubernetes controller and tool for one-way encrypted Secrets.
  featured: false
  home-url: https://github.com/bitnami-labs/sealed-secrets
  categories:
    - security
