# syntax=dhi.io/build:2-helm3

name: Piraeus HA Controller Helm chart 1.x
image: dhi.io/piraeus-ha-controller-chart
variant: helm
tags:
  - 1.3.1
platforms:
  - linux/amd64
vars:
  CHART_COMMIT_SHA: 4a1b921b09910b48c76c1dde1276a2f829cd7f90
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_REFERENCE: dhi/helm:3.20.0-debian13-dev@sha256:7069456b86d57f9f2efaf7561c7f78097c6a4382a6e3420d23680ce61a045f34
  PIRAEUS_HA_CONTROLLER_REFERENCE: dhi/piraeus-ha-controller:1.3.2-debian13@sha256:47c8a32f0468a794d13b6176bb00103ed5f8d27c18e37f69851438afd9725380
  SEMVER_MAJOR_MINOR_VERSION: "1.3"
  SEMVER_MAJOR_VERSION: "1"
  SEMVER_VERSION: 1.3.1
  VERSION: 1.3.1
contents:
  builds:
    - name: piraeus-ha-controller
      uses: dhi.io/helm:3.20.0-debian13-dev@sha256:7069456b86d57f9f2efaf7561c7f78097c6a4382a6e3420d23680ce61a045f34
      contents:
        packages:
          - bash
          - build-essential
          - coreutils
          - grep
          - libc-bin
          - sed
        files:
          - url: git+https://github.com/piraeusdatastore/helm-charts.git#piraeus-ha-controller-1.3.1
            checksum: 4a1b921b09910b48c76c1dde1276a2f829cd7f90
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/piraeus-ha-controller
          with:
            chart:
              appRef: piraeus-ha-controller
              description: Docker Hardened Images Helm chart for Piraeus HA Controller
              images:
                - name: piraeus-ha-controller
                  ref: dhi/piraeus-ha-controller:1.3.2-debian13@sha256:47c8a32f0468a794d13b6176bb00103ed5f8d27c18e37f69851438afd9725380
              name: piraeus-ha-controller-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/piraeusdatastore/helm-charts
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/piraeus-ha-controller
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: lint
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/charts
          with:
            chart: piraeus-ha-controller
            cmd: lint .
        - name: package
          uses: helm/package@v1
          work-dir: ${source.dir}/helm-charts/charts
          with:
            chart: piraeus-ha-controller
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/piraeus-ha-controller/config
