image:
  registry: ${cert-manager-controller.registry}
  repository: ${cert-manager-controller.repository}
  tag: ${cert-manager-controller.tag}@${cert-manager-controller.digest}

cainjector:
  image:
    registry: ${cert-manager-cainjector.registry}
    repository: ${cert-manager-cainjector.repository}
    tag: ${cert-manager-cainjector.tag}@${cert-manager-cainjector.digest}
  securityContext:
    runAsUser: 65532
    runAsGroup: 65532
    fsGroup: 65532

webhook:
  image:
    registry: ${cert-manager-webhook.registry}
    repository: ${cert-manager-webhook.repository}
    tag: ${cert-manager-webhook.tag}@${cert-manager-webhook.digest}
  securityContext:
    runAsUser: 65532
    runAsGroup: 65532
    fsGroup: 65532

acmesolver:
  image:
    registry: ${cert-manager-acmesolver.registry}
    repository: ${cert-manager-acmesolver.repository}
    tag: ${cert-manager-acmesolver.tag}@${cert-manager-acmesolver.digest}

startupapicheck:
  image:
    registry: ${cert-manager-startupapicheck.registry}
    repository: ${cert-manager-startupapicheck.repository}
    tag: ${cert-manager-startupapicheck.tag}@${cert-manager-startupapicheck.digest}
  securityContext:
    runAsUser: 65532
    runAsGroup: 65532
    fsGroup: 65532

securityContext:
  runAsUser: 65532
  runAsGroup: 65532
  fsGroup: 65532
