metadata:
  display-name: Fluent Bit Helm chart
  short-description: Fluent Bit is an open source data collector for unified logging layer.
  featured: false
  home-url: https://fluentbit.io/
  categories:
    - monitoring-and-observability
