image:
  registry: ${alloy.registry}
  repository: ${alloy.repository}
  tag: ${alloy.tag}
  digest: ${alloy.digest}

configReloader:
  image:
    registry: ${prometheus-config-reloader.registry}
    repository: ${prometheus-config-reloader.repository}
    tag: ${prometheus-config-reloader.tag}
    digest: ${prometheus-config-reloader.digest}
