global:
  podSecurityContext:
    runAsNonRoot: true
    runAsUser: 473
    runAsGroup: 473
    fsGroup: 473

image:
  registry: ${alloy.registry}
  repository: ${alloy.repository}
  tag: ${alloy.tag}
  digest: ${alloy.digest}

configReloader:
  image:
    registry: ${prometheus-config-reloader.registry}
    repository: ${prometheus-config-reloader.repository}
    tag: ${prometheus-config-reloader.tag}
    digest: ${prometheus-config-reloader.digest}
  securityContext:
    runAsNonRoot: true
    runAsUser: 65532
    runAsGroup: 65532
