# syntax=dhi.io/build:2-helm3

name: Grafana Rollout Operator Helm chart 0.x
image: dhi.io/grafana-rollout-operator-chart
variant: helm
tags:
  - 0.43.0
platforms:
  - linux/amd64
vars:
  CHART_COMMIT_SHA: 9ddb81243bfc8aea3bf3d0a9954451d407cee1c6
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_REFERENCE: dhi/helm:3.20.0-debian13-dev@sha256:7069456b86d57f9f2efaf7561c7f78097c6a4382a6e3420d23680ce61a045f34
  ROLLOUT_OPERATOR_REFERENCE: dhi/grafana-rollout-operator:0.35.0-debian13@sha256:844adadfdf98d8da00a95641dbb3205aef2c7c210182d94aa07ef7dcf1f906c3
  SEMVER_MAJOR_MINOR_VERSION: "0.43"
  SEMVER_MAJOR_VERSION: "0"
  SEMVER_VERSION: 0.43.0
  VERSION: 0.43.0
contents:
  builds:
    - name: grafana-rollout-operator-chart
      uses: dhi.io/helm:3.20.0-debian13-dev@sha256:7069456b86d57f9f2efaf7561c7f78097c6a4382a6e3420d23680ce61a045f34
      work-dir: ${source.dir}/helm-charts/charts/rollout-operator
      contents:
        files:
          - url: git+https://github.com/grafana/helm-charts.git#rollout-operator-0.43.0
            checksum: 9ddb81243bfc8aea3bf3d0a9954451d407cee1c6
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          with:
            chart:
              appRef: grafana-rollout-operator
              description: Docker Hardened Images Helm chart for Grafana Rollout Operator
              images:
                - name: grafana-rollout-operator
                  ref: dhi/grafana-rollout-operator:0.35.0-debian13@sha256:844adadfdf98d8da00a95641dbb3205aef2c7c210182d94aa07ef7dcf1f906c3
              name: grafana-rollout-operator-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/grafana/helm-charts
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: update dependencies
          uses: helm/cmd@v1
          privileged: true
          with:
            chart: .
            cmd: dependency update
        - name: lint
          uses: helm/cmd@v1
          with:
            chart: .
            cmd: lint .
        - name: package
          uses: helm/package@v1
          with:
            chart: .
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/grafana-rollout-operator/config
