metadata:
  display-name: Istio Discovery (istiod) Helm chart
  short-description: Helm chart for the Istio control plane (istiod) from the Istio project.
  featured: false
  home-url: https://istio.io/latest/
  categories:
    - networking
