metadata:
  display-name: External DNS Helm chart
  short-description: ExternalDNS synchronizes exposed Kubernetes Services and Ingresses with DNS providers.
  featured: false
  home-url: https://kubernetes-sigs.github.io/external-dns
  categories:
    - developer-tools
    - networking
