metadata:
  display-name: Prometheus
  short-description: Prometheus is a systems and service monitoring system that records metrics in a time series database.
  featured: false
  home-url: https://prometheus.io/
  categories:
    - databases-and-storage
    - monitoring-and-observability
