metadata:
  display-name: Istio Ztunnel Helm chart
  short-description: The ztunnel component of Istio's ambient mesh
  featured: false
  home-url: https://istio.io/latest/
  categories:
    - networking
