metadata:
  display-name: Prometheus Node Exporter Helm chart
  short-description: Exports hardware- and OS-level metrics from a host for scraping by Prometheus.
  featured: false
  home-url: https://github.com/prometheus/node_exporter
  categories:
    - monitoring-and-observability
