# syntax=dhi.io/build:2-helm3

name: Istio Base Helm chart 1.x
image: dhi.io/istio-base-chart
variant: helm
tags:
  - 1.0.0
platforms:
  - linux/amd64
vars:
  CHART_COMMIT_SHA: d79c90f27776e65c20ffdc5077afdb8662652480
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_REFERENCE: dhi/helm:3.20.0-debian13-dev@sha256:7069456b86d57f9f2efaf7561c7f78097c6a4382a6e3420d23680ce61a045f34
  SEMVER_MAJOR_MINOR_VERSION: "1.0"
  SEMVER_MAJOR_VERSION: "1"
  SEMVER_VERSION: 1.0.0
  VERSION: 1.0.0
contents:
  builds:
    - name: istio-base-chart
      uses: dhi.io/helm:3.20.0-debian13-dev@sha256:7069456b86d57f9f2efaf7561c7f78097c6a4382a6e3420d23680ce61a045f34
      contents:
        files:
          - url: git+https://github.com/istio/istio.git#d79c90f27776e65c20ffdc5077afdb8662652480
            checksum: d79c90f27776e65c20ffdc5077afdb8662652480
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/manifests/charts/base
          with:
            chart:
              description: Docker Hardened Images Helm chart for Istio Base
              name: istio-base-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/istio/istio/tree/master/manifests/charts/base
            cmd: prepare
            registry: dhi.io
        - name: lint
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/manifests/charts
          with:
            chart: base
            cmd: lint .
        - name: package
          uses: helm/package@v1
          work-dir: ${source.dir}/helm-charts/manifests/charts
          with:
            chart: base
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/istio-base/config
