metadata:
  display-name: Reloader Helm Chart
  short-description: A Kubernetes controller to watch changes in ConfigMap and Secrets and do rolling upgrades on Pods with their associated Deployment, StatefulSet, DaemonSet and DeploymentConfig
  featured: false
  home-url: https://github.com/stakater/Reloader
  categories:
    - developer-tools
