metadata:
  display-name: configmap-reload
  short-description: A simple binary to trigger a reload when Kubernetes ConfigMaps or Secrets are updated. It watches mounted volume dirs and notifies the target process that the config map has been changed.
  featured: false
  home-url: https://github.com/jimmidyson/configmap-reload
  categories:
    - developer-tools
