# syntax=dhi.io/build:2-helm3

name: Argo CD Helm chart 9.x
image: dhi.io/argocd-chart
variant: helm
tags:
  - 9.4.4
platforms:
  - linux/amd64
vars:
  ARGOCD_REFERENCE: dhi/argocd:3.2.7-debian13@sha256:3b635c2d5063bbe655f0329e7884bcabcb564a2ab97f35a52120ed87408ea7cf
  CHART_COMMIT_SHA: 522c342ec0e38978d8ae47690608a4aedd838727
  DEX_REFERENCE: dhi/dex:2.45.0-debian13@sha256:81464b9c5dea4a3932c2683468677914d40b5ca8b54aa0e47f629af0aa22e9ec
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HAPROXY_CHART_REFERENCE: dhi/haproxy-chart:1.28.0@sha256:5dc51125f908e4e351b48c4a58741260fbd8832d8cdf588a61266f95f7c36ab7
  HELM_REFERENCE: dhi/helm:3.20.0-debian13-dev@sha256:7069456b86d57f9f2efaf7561c7f78097c6a4382a6e3420d23680ce61a045f34
  REDIS_CHART_REFERENCE: dhi/redis-chart:23.0.5@sha256:6db1a22247b6049d8ed5b4114b7abdf07871f7643577187bbacdb47aa73ec22c
  REDIS_EXPORTER_REFERENCE: dhi/redis-exporter:1.81.0-debian13@sha256:c4c275afff755f007c878764941f45f25540f3f8333f90df68470b4be5ff8f0a
  REDIS_REFERENCE: dhi/redis:8.2.5-debian13-compat@sha256:e7c8d68e4f739d5298c4920a1fed72f4dade3c50854e1650d678d6fcd115858c
  SEMVER_MAJOR_MINOR_VERSION: "9.4"
  SEMVER_MAJOR_VERSION: "9"
  SEMVER_VERSION: 9.4.4
  VERSION: 9.4.4
contents:
  builds:
    - name: argocd
      uses: dhi.io/helm:3.20.0-debian13-dev@sha256:7069456b86d57f9f2efaf7561c7f78097c6a4382a6e3420d23680ce61a045f34
      contents:
        packages:
          - bash
          - build-essential
          - coreutils
          - grep
          - libc-bin
          - sed
        files:
          - url: git+https://github.com/argoproj/argo-helm#argo-cd-9.4.4
            checksum: 522c342ec0e38978d8ae47690608a4aedd838727
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/argo-cd
          with:
            chart:
              appRef: argocd
              dependencies:
                - alias: redis-ha
                  condition: redis-ha.enabled
                  name: redis-ha
                  ref: dhi/redis-chart:23.0.5@sha256:6db1a22247b6049d8ed5b4114b7abdf07871f7643577187bbacdb47aa73ec22c
                - alias: haproxy
                  condition: haproxy.enabled
                  name: haproxy
                  ref: dhi/haproxy-chart:1.28.0@sha256:5dc51125f908e4e351b48c4a58741260fbd8832d8cdf588a61266f95f7c36ab7
              description: Docker Hardened Images Helm chart for Argo CD
              images:
                - name: argocd
                  ref: dhi/argocd:3.2.7-debian13@sha256:3b635c2d5063bbe655f0329e7884bcabcb564a2ab97f35a52120ed87408ea7cf
                - name: dex
                  ref: dhi/dex:2.45.0-debian13@sha256:81464b9c5dea4a3932c2683468677914d40b5ca8b54aa0e47f629af0aa22e9ec
                - name: redis
                  ref: dhi/redis:8.2.5-debian13-compat@sha256:e7c8d68e4f739d5298c4920a1fed72f4dade3c50854e1650d678d6fcd115858c
                - name: redis-exporter
                  ref: dhi/redis-exporter:1.81.0-debian13@sha256:c4c275afff755f007c878764941f45f25540f3f8333f90df68470b4be5ff8f0a
              name: argocd-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/argoproj/argo-helm
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/argo-cd
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: update values
          uses: yq/patch@v1
          work-dir: ${source.dir}/helm-charts/charts
          with:
            file: argo-cd/values.yaml
            patches:
              - del(.redis-ha.image)
              - del(.redis-ha.exporter.image)
              - del(.redis-ha.exporter.tag)
              - del(.redis-ha.haproxy.image.repository)
              - del(.redis-ha.haproxy)
              - del(.redis-ha.redis.masterGroupName)
              - del(.redis-ha.redis.config)
              - del(.redis-ha.hardAntiAffinity)
              - del(.redis-ha.additionalAffinities)
              - del(.redis-ha.affinity)
              - del(.redis-ha.tolerations)
              - del(.redis-ha.topologySpreadConstraints)
              - del(.redis-ha.containerSecurityContext)
        - name: Patch templates
          work-dir: ${source.dir}/helm-charts/charts/argo-cd/templates
          runs: |
            set -eux -o pipefail

            sed -i 's/$redisHa.haproxy.enabled/.Values.haproxy.enabled/' _helpers.tpl
            sed -i 's/redis-ha.fullname/common.names.fullname/' _helpers.tpl
        - name: helm login
          uses: helm/login@v1
          with:
            registry: dhi.io
        - name: update dependencies
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/charts
          privileged: true
          with:
            chart: argo-cd
            cmd: dependency update
        - name: lint
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/charts
          with:
            chart: argo-cd
            cmd: lint .
        - name: package
          uses: helm/package@v1
          work-dir: ${source.dir}/helm-charts/charts
          with:
            chart: argo-cd
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/argocd/config
