metadata:
  display-name: Azure Service Operator Helm chart
  short-description: Azure Service Operator allows you to create Azure resources using kubectl.
  featured: false
  home-url: https://azure.github.io/azure-service-operator/
  categories:
    - developer-tools
