controller:
  image:
    registry: ${argo-rollouts.registry}
    repository: ${argo-rollouts.repository}
    tag: ${argo-rollouts.tag}@${argo-rollouts.digest}

dashboard:
  image:
    registry: ${kubectl-argo-rollouts.registry}
    repository: ${kubectl-argo-rollouts.repository}
    tag: ${kubectl-argo-rollouts.tag}@${kubectl-argo-rollouts.digest}

# Upstream runs as non root by default, so we don't need to set nonroot security context
