# syntax=dhi.io/build:2-helm3

name: Cert-Manager Helm chart VERSION:^v?([0-9]+).*$.x
image: dhi.io/cert-manager-chart
variant: helm
tags:
  - 1.19.3
platforms:
  - linux/amd64
vars:
  CERT_MANAGER_ACMESOLVER_REFERENCE: dhi/cert-manager-acmesolver:1.19.2-debian13@sha256:d26bfe3c967fb5a61a35f54be67e156fc7f1279a2c1028be267b932fa68de6f0
  CERT_MANAGER_CAINJECTOR_REFERENCE: dhi/cert-manager-cainjector:1.19.2-debian13@sha256:b5ab9b82a5a150c6753708405dd014c4da526da4d2ace5142357736d43bfcf04
  CERT_MANAGER_COMMIT_SHA: d4faed26ae12115cceb807cdc12507ebc28980e2
  CERT_MANAGER_CONTROLLER_REFERENCE: dhi/cert-manager-controller:1.19.2-debian13@sha256:0f48fa48b59f86129783d6a1ad9bd1be7f9cfb618c516f22f976f209514e08f7
  CERT_MANAGER_STARTUPAPICHECK_REFERENCE: dhi/cert-manager-startupapicheck:1.19.2-debian13@sha256:b783c24de5439f5af6d8750ce2aef52d6ea9f2ac911fef13cee634ec13acdeda
  CERT_MANAGER_VERSION: 1.19.3
  CERT_MANAGER_WEBHOOK_REFERENCE: dhi/cert-manager-webhook:1.19.2-debian13@sha256:1dc1c3850af91cf0ae4176d92c3400a22d3f57dcad3f132248864861bef7e2aa
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_REFERENCE: dhi/helm:3.20.0-debian13-dev@sha256:7cb2e3261500133ea8b5a670b731b6d200e5637b9b1d8451ccc759c358fca0dc
  SEMVER_MAJOR_MINOR_VERSION: ${VERSION:^v?([0-9]+\.[0-9]+).*$}
  SEMVER_MAJOR_VERSION: ${VERSION:^v?([0-9]+).*$}
  SEMVER_VERSION: ${VERSION:^v?([0-9]+\.[0-9]+\.[0-9]+).*$}
contents:
  builds:
    - name: cert-manager
      uses: dhi.io/helm:3.20.0-debian13-dev@sha256:7cb2e3261500133ea8b5a670b731b6d200e5637b9b1d8451ccc759c358fca0dc
      contents:
        packages:
          - make
          - curl
          - git
        files:
          - url: git+https://github.com/cert-manager/cert-manager.git#v1.19.3
            checksum: d4faed26ae12115cceb807cdc12507ebc28980e2
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: Make Chart from template
          work-dir: ${source.dir}/helm-charts/
          privileged: true
          runs: |
            set -eux -o pipefail

            make _bin/helm/cert-manager/Chart.yaml
            cp _bin/helm/cert-manager/Chart.yaml deploy/charts/cert-manager/Chart.yaml
            rm deploy/charts/cert-manager/Chart.template.yaml
        - name: prepare chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/deploy/charts/cert-manager
          with:
            chart:
              appRef: cert-manager-controller
              description: Docker Hardened Images Helm chart for Cert-Manager
              images:
                - name: cert-manager-controller
                  ref: dhi/cert-manager-controller:1.19.2-debian13@sha256:0f48fa48b59f86129783d6a1ad9bd1be7f9cfb618c516f22f976f209514e08f7
                - name: cert-manager-cainjector
                  ref: dhi/cert-manager-cainjector:1.19.2-debian13@sha256:b5ab9b82a5a150c6753708405dd014c4da526da4d2ace5142357736d43bfcf04
                - name: cert-manager-acmesolver
                  ref: dhi/cert-manager-acmesolver:1.19.2-debian13@sha256:d26bfe3c967fb5a61a35f54be67e156fc7f1279a2c1028be267b932fa68de6f0
                - name: cert-manager-startupapicheck
                  ref: dhi/cert-manager-startupapicheck:1.19.2-debian13@sha256:b783c24de5439f5af6d8750ce2aef52d6ea9f2ac911fef13cee634ec13acdeda
                - name: cert-manager-webhook
                  ref: dhi/cert-manager-webhook:1.19.2-debian13@sha256:1dc1c3850af91cf0ae4176d92c3400a22d3f57dcad3f132248864861bef7e2aa
              name: cert-manager-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/cert-manager/cert-manager
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/deploy/charts/cert-manager
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: lint
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/deploy/charts/
          with:
            chart: cert-manager
            cmd: lint .
        - name: package
          uses: helm/package@v1
          work-dir: ${source.dir}/helm-charts/deploy/charts
          with:
            chart: cert-manager
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/cert-manager/config
