image:
  registry: ${grafana-agent.registry}
  repository: ${grafana-agent.repository}
  tag: ${grafana-agent.tag}
  digest: ${grafana-agent.digest}

configReloader:
  image:
    registry: ${configmap-reload.registry}
    repository: ${configmap-reload.repository}
    tag: ${configmap-reload.tag}
    digest: ${configmap-reload.digest}
