metadata:
  display-name: Istio Base Helm chart
  short-description: This chart installs resources shared by all Istio revisions. This includes Istio CRDs.
  featured: false
  home-url: https://github.com/istio/istio/tree/master/manifests/charts/base/README.md
  categories:
    - monitoring-and-observability
    - networking
    - security
