image:
  registry: ${valkey.registry}
  repository: ${valkey.repository}
  tag: ${valkey.tag}@${valkey.digest}

metrics:
  exporter:
    image:
      registry: ${redis-exporter.registry}
      repository: ${redis-exporter.repository}
      tag: ${redis-exporter.tag}@${redis-exporter.digest}
