image:
  repository: ${vector.registry}/${vector.repository}
  tag: ${vector.tag}
  sha: ${vector.digest}

haproxy:
  image:
    repository: ${haproxy.registry}/${haproxy.repository}
    tag: ${haproxy.tag}@${haproxy.digest}
