image:
  registry: ${oauth2-proxy.registry}
  repository: ${oauth2-proxy.repository}
  tag: ${oauth2-proxy.tag}@${oauth2-proxy.digest}

initContainers:
  waitForRedis:
    image:
      repository: ${alpine-base.registry}/${alpine-base.repository}
      tag: ${alpine-base.tag}@${alpine-base.digest}
