# syntax=dhi.io/build:2-helm3

name: Vault Helm chart 0.x
image: dhi.io/vault-chart
variant: helm
tags:
  - 0.31.0
platforms:
  - linux/amd64
vars:
  CHART_COMMIT_SHA: da81d965d3968a19a3da9286f0993da5cd0866de
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_REFERENCE: dhi/helm:3.19.4-debian13-dev@sha256:4a591aa3cad9e5a0b82d3503e6140956db99735b68351b7b223514220873df4c
  SEMVER_MAJOR_MINOR_VERSION: "0.31"
  SEMVER_MAJOR_VERSION: "0"
  SEMVER_VERSION: 0.31.0
  VAULT_CSI_PROVIDER_REFERENCE: dhi/vault-csi-provider:1.7.0-debian13@sha256:382f2f64b266d707fb53789887947ad1fbd28184e804f3765369db6cb7a4c3da
  VAULT_HELM_REFERENCE: dhi/vault:1.21.2-debian13-helm@sha256:aacfde1cf6ad76a92a217a98f52919079ed3497eeb35eb5063ffd70a99d2eb8e
  VAULT_K8S_REFERENCE: dhi/vault-k8s:1.7.2-debian13@sha256:0b36ae3005f92188490b0808bcf967f1a79044005d61960556bc0108237c372d
  VAULT_REFERENCE: dhi/vault:1.21.2-debian13@sha256:3b1485181eefcc6996b266a7c09f5b06d1ef173557e42d3f97c9003ef61d6926
  VERSION: 0.31.0
contents:
  builds:
    - name: vault
      uses: dhi.io/helm:3.19.4-debian13-dev@sha256:4a591aa3cad9e5a0b82d3503e6140956db99735b68351b7b223514220873df4c
      contents:
        packages:
          - bash
          - build-essential
          - coreutils
          - grep
          - libc-bin
          - sed
        files:
          - url: git+https://github.com/hashicorp/vault-helm.git#v0.31.0
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts
          with:
            chart:
              appRef: vault
              description: Docker Hardened Images Helm chart for Vault
              images:
                - name: vault
                  ref: dhi/vault:1.21.2-debian13@sha256:3b1485181eefcc6996b266a7c09f5b06d1ef173557e42d3f97c9003ef61d6926
                - name: vault-helm
                  ref: dhi/vault:1.21.2-debian13-helm@sha256:aacfde1cf6ad76a92a217a98f52919079ed3497eeb35eb5063ffd70a99d2eb8e
                - name: vault-k8s
                  ref: dhi/vault-k8s:1.7.2-debian13@sha256:0b36ae3005f92188490b0808bcf967f1a79044005d61960556bc0108237c372d
                - name: vault-csi-provider
                  ref: dhi/vault-csi-provider:1.7.0-debian13@sha256:382f2f64b266d707fb53789887947ad1fbd28184e804f3765369db6cb7a4c3da
              name: vault-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/hashicorp/vault-helm
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: update dependencies
          uses: helm/cmd@v1
          with:
            chart: ${source.dir}/helm-charts
            cmd: dependency update
        - name: lint
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts
          with:
            chart: .
            cmd: lint .
        - name: package
          uses: helm/package@v1
          with:
            chart: ${source.dir}/helm-charts
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/vault/config
