metadata:
  display-name: Metrics Server Helm chart
  short-description: Metrics Server is a scalable, efficient source of container resource metrics for Kubernetes built-in autoscaling pipelines. It collects resource metrics from Kubelets and exposes them in Kubernetes apiserver through Metrics API for use by Horizontal Pod Autoscaler and Vertical Pod Autoscaler.
  featured: false
  home-url: https://kubernetes-sigs.github.io/metrics-server/
  categories:
    - monitoring-and-observability
