server:
  datasource:
    url: http://localhost # This is a default value because this field is required for unit testing.
  image:
    registry: ${victoriametrics-vmalert.registry}
    repository: ${victoriametrics-vmalert.repository}
    tag: ${victoriametrics-vmalert.tag}
  podSecurityContext:
    enabled: true
    fsGroup: 65532
  securityContext:
    enabled: true
    runAsNonRoot: true
    runAsUser: 65532
    runAsGroup: 65532

alertmanager:
  image:
    registry: ${alertmanager.registry}
    repository: ${alertmanager.repository}
    tag: ${alertmanager.tag}@${alertmanager.digest}
  podSecurityContext:
    enabled: true
    fsGroup: 65532
  securityContext:
    enabled: true
    runAsNonRoot: true
    runAsUser: 65532
    runAsGroup: 65532
