# syntax=dhi.io/build:2-helm3

name: Istio Discovery (istiod) Helm chart 1.x
image: dhi.io/istio-discovery-chart
variant: helm
tags:
  - 1.28.4
platforms:
  - linux/amd64
vars:
  CHART_COMMIT_SHA: 0cc9a3e0b248766541f79f0256668e84b02d4bc8
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_REFERENCE: dhi/helm:3.20.0-debian13-dev@sha256:7069456b86d57f9f2efaf7561c7f78097c6a4382a6e3420d23680ce61a045f34
  ISTIO_PILOT_REFERENCE: dhi/istio-pilot:1.28.4-debian13@sha256:48d53ba714f552c8b76c83f8fa5146567ad805d318c8a1ef613a0670e642f528
  ISTIO_PROXYV2_REFERENCE: dhi/istio-proxyv2:1.28.4-debian13@sha256:66b052684ca549a190ea8f713b1d2fe40d9b9e3ebca9f56bd8f308d77123699d
  SEMVER_MAJOR_MINOR_VERSION: "1.28"
  SEMVER_MAJOR_VERSION: "1"
  SEMVER_VERSION: 1.28.4
  VERSION: 1.28.4
contents:
  builds:
    - name: istio-discovery
      uses: dhi.io/helm:3.20.0-debian13-dev@sha256:7069456b86d57f9f2efaf7561c7f78097c6a4382a6e3420d23680ce61a045f34
      work-dir: /src/go/github.com/istio/istio/manifests/charts/istio-control/istio-discovery
      contents:
        files:
          - url: git+https://github.com/istio/istio.git#1.28.4
            path: /src/go/github.com/istio/istio
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          with:
            chart:
              appRef: pilot
              description: Docker Hardened Images Helm chart for Istio Discovery (istiod)
              images:
                - name: pilot
                  ref: dhi/istio-pilot:1.28.4-debian13@sha256:48d53ba714f552c8b76c83f8fa5146567ad805d318c8a1ef613a0670e642f528
                - name: proxyv2
                  ref: dhi/istio-proxyv2:1.28.4-debian13@sha256:66b052684ca549a190ea8f713b1d2fe40d9b9e3ebca9f56bd8f308d77123699d
              name: istio-discovery-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/istio/istio
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: lint
          uses: helm/cmd@v1
          with:
            chart: .
            cmd: lint .
        - name: package
          uses: helm/package@v1
          with:
            chart: .
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/istio-discovery/config
