# syntax=dhi.io/build:2-debian13

name: Prometheus Adapter 0.x
image: dhi.io/prometheus-adapter
variant: runtime
tags:
  - "0"
  - "0.12"
  - 0.12.0
  - 0-debian13
  - 0.12-debian13
  - 0.12.0-debian13
platforms:
  - linux/amd64
  - linux/arm64
dates:
  release: "2024-11-04"
vars:
  BASE_DIGEST: sha256:74fc43fa240887b8159970e434244039aab0c6efaaa9cf044004cdc22aa2a34d
  BASE_TAG: 20250419-debian13
  COMMIT_SHA: 17cef511b1854441490bceeca7a710a04ce091ad
  GOLANG_REFERENCE: dhi/golang:1.25.7-debian13-dev@sha256:d241d31631f6bcfdef4f42f70083bb06d51e6401d9ce172a05b9ba37f27c2940
  SEMVER_MAJOR_MINOR_VERSION: "0.12"
  SEMVER_MAJOR_VERSION: "0"
  SEMVER_VERSION: 0.12.0
  VERSION: 0.12.0
contents:
  packages:
    - '!base-files'
  builds:
    - name: prometheus-adapter
      uses: dhi.io/golang:1.25.7-debian13-dev@sha256:d241d31631f6bcfdef4f42f70083bb06d51e6401d9ce172a05b9ba37f27c2940
      work-dir: /go/src/github.com/kubernetes-sigs/prometheus-adapter
      caches:
        - path: /go/pkg/mod
      contents:
        files:
          - url: git+https://github.com/kubernetes-sigs/prometheus-adapter.git#v0.12.0
            checksum: 17cef511b1854441490bceeca7a710a04ce091ad
            path: /go/src/github.com/kubernetes-sigs/prometheus-adapter
            spdx:
              name: prometheus-adapter
              version: 0.12.0
              packages:
                - name: prometheus-adapter
                  purl: pkg:golang/sigs.k8s.io/prometheus-adapter@0.12.0
                  license: Apache-2.0
            uid: 0
            gid: 0
      pipeline:
        - name: update go dependencies
          uses: go/bump@v1
          with:
            deps:
              - golang.org/x/oauth2@v0.27.0
              - golang.org/x/net@v0.45.0
              - golang.org/x/crypto@v0.45.0
            download: true
        - name: unit tests
          runs: |
            set -eux -o pipefail

            CGO_ENABLED=0 go test ./cmd/... ./pkg/...
        - name: build
          uses: go/build@v1
          with:
            output: ${target.dir}/usr/local/bin/adapter
            packages: ./cmd/adapter
      outputs:
        - source: ${target.dir}/usr/local/bin/adapter
          target: /usr/local/bin/adapter
          uid: 0
          gid: 0
          mode: "0755"
        - source: /opt/docker/sbom/prometheus-adapter
          target: /opt/docker/sbom/prometheus-adapter
          uid: 0
          gid: 0
  artifacts:
    - name: dhi.io/static:20250419-debian13@sha256:74fc43fa240887b8159970e434244039aab0c6efaaa9cf044004cdc22aa2a34d
      includes:
        - bin
        - etc
        - home
        - lib
        - lib64
        - opt
        - sbin
        - tmp
        - usr
        - var
      excludes:
        - etc/group
        - etc/os-release
        - etc/passwd
        - var/lib/dpkg/status
      uid: 0
      gid: 0
accounts:
  run-as: nonroot
  users:
    - name: nonroot
      uid: 65532
      gid: 65532
  groups:
    - name: nonroot
      gid: 65532
      members:
        - nonroot
os-release:
  name: Docker Hardened Images (Debian)
  id: debian
  version-id: "13"
  version-codename: trixie
  pretty-name: Docker Hardened Images/Debian GNU/Linux 13 (trixie)
  home-url: https://docker.com/products/hardened-images/
  bug-report-url: https://docker.com/support/
paths:
  - type: symlink
    path: /adapter
    uid: 0
    gid: 0
    source: /usr/local/bin/adapter
annotations:
  org.opencontainers.image.description: A minimal Prometheus Adapter image
  org.opencontainers.image.licenses: Apache-2.0
entrypoint:
  - /adapter
