metadata:
  display-name: Kubernetes Cluster Autoscaler Helm Chart
  short-description: Cluster Autoscaler is a tool that automatically adjusts the size of the Kubernetes cluster.
  featured: false
  home-url: https://github.com/kubernetes/autoscaler/tree/master/cluster-autoscaler
  categories:
    - integration-and-delivery
    - monitoring-and-observability
    - networking
