metadata:
  display-name: Kube State Metrics Helm chart
  short-description: an add-on agent to generate and expose cluster-level metrics
  featured: false
  home-url: https://kubernetes.io/docs/concepts/cluster-administration/kube-state-metrics/
  categories:
    - monitoring-and-observability
