metadata:
  display-name: Kube Prometheus Stack Helm chart
  short-description: End-to-end Kubernetes cluster monitoring with Prometheus using the Prometheus Operator, including Alertmanager, Grafana, and exporters.
  featured: false
  home-url: https://github.com/prometheus-community/helm-charts
  categories:
    - monitoring-and-observability
