metadata:
  display-name: OAuth2 Proxy Helm chart
  short-description: A reverse proxy that provides authentication using OAuth2 and OIDC providers.
  featured: false
  home-url: https://github.com/oauth2-proxy/oauth2-proxy
  categories:
    - security
