image:
  repository: ${metrics-server.registry}/${metrics-server.repository}
  tag: ${metrics-server.tag}@${metrics-server.digest}

addonResizer:
  image:
    repository: "#THIS IMAGE IS NOT IN THE DHI CATALOG YET, PLEASE CONTACT THE DOCKER TEAM IF NEEDED"
