# syntax=dhi.io/build:2-helm3

name: Stakater Reloader Helm chart 2.x
image: dhi.io/stakater-reloader-chart
variant: helm
tags:
  - 2.2.8
platforms:
  - linux/amd64
vars:
  CHART_COMMIT_SHA: 9aa957c8398544a6c73766b26c8b804bc7f23e89
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_REFERENCE: dhi/helm:3.20.0-debian13-dev@sha256:7069456b86d57f9f2efaf7561c7f78097c6a4382a6e3420d23680ce61a045f34
  RELOADER_REFERENCE: dhi/stakater-reloader:1.4.12-debian13@sha256:b7ad2267b7e227e8976ae67082909c61a1ebd515375c5ec5825ddcec56a1161c
  SEMVER_MAJOR_MINOR_VERSION: "2.2"
  SEMVER_MAJOR_VERSION: "2"
  SEMVER_VERSION: 2.2.8
  VERSION: 2.2.8
contents:
  builds:
    - name: stakater-reloader-chart
      uses: dhi.io/helm:3.20.0-debian13-dev@sha256:7069456b86d57f9f2efaf7561c7f78097c6a4382a6e3420d23680ce61a045f34
      contents:
        files:
          - url: git+https://github.com/stakater/Reloader.git#chart-v2.2.8
            checksum: 9aa957c8398544a6c73766b26c8b804bc7f23e89
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/deployments/kubernetes/chart/reloader
          with:
            chart:
              appRef: stakater-reloader
              description: Docker Hardened Images Helm chart for Stakater Reloader
              images:
                - name: stakater-reloader
                  ref: dhi/stakater-reloader:1.4.12-debian13@sha256:b7ad2267b7e227e8976ae67082909c61a1ebd515375c5ec5825ddcec56a1161c
              name: stakater-reloader-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/stakater/Reloader
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/deployments/kubernetes/chart/reloader
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: update dependencies
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/deployments/kubernetes/chart
          privileged: true
          with:
            chart: reloader
            cmd: dependency update
        - name: lint
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/deployments/kubernetes/chart
          with:
            chart: reloader
            cmd: lint .
        - name: package
          uses: helm/package@v1
          work-dir: ${source.dir}/helm-charts/deployments/kubernetes/chart
          with:
            chart: reloader
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/stakater-reloader/config
