metadata:
  display-name: Piraeus HA Controller Helm chart
  short-description: High Availability Controller for stateful workloads using DRBD storage provisioned by Piraeus.
  featured: false
  home-url: https://github.com/piraeusdatastore/piraeus-ha-controller
  categories:
    - databases-and-storage
