metadata:
  display-name: Prometheus Operator
  short-description: Kubernetes operator for managing Prometheus.
  featured: false
  home-url: https://prometheus-operator.dev/
  categories:
    - monitoring-and-observability
