image:
  registry: ${node-exporter.registry}
  repository: ${node-exporter.repository}
  tag: ${node-exporter.tag}
  digest: ${node-exporter.digest}

kubeRBACProxy:
  image:
    registry: ${kube-rbac-proxy.registry}
    repository: ${kube-rbac-proxy.repository}
    tag: ${kube-rbac-proxy.tag}@${kube-rbac-proxy.digest}
