metadata:
  display-name: VictoriaMetrics Cluster Helm chart
  short-description: A observability solution and time series database
  featured: false
  home-url: https://victoriametrics.com
  categories:
    - monitoring-and-observability
