# syntax=dhi.io/build:2-debian13

name: Prometheus Operator 0.x
image: dhi.io/prometheus-operator
variant: runtime
tags:
  - "0"
  - "0.88"
  - 0.88.0
  - 0-debian13
  - 0.88-debian13
  - 0.88.0-debian13
platforms:
  - linux/amd64
  - linux/arm64
vars:
  BASE_DIGEST: sha256:74fc43fa240887b8159970e434244039aab0c6efaaa9cf044004cdc22aa2a34d
  BASE_TAG: 20250419-debian13
  COMMIT_SHA: 21974db4687ad80a6ea79af66d410db54510e35e
  GO_REFERENCE: dhi/golang:1.25.5-debian13-dev@sha256:a45faad20adc1286eef26b1f30e170b54791c217ce69457784de66b0a13d1fe6
  GO_VERSION: 1.25.5
  SEMVER_MAJOR_MINOR_VERSION: "0.88"
  SEMVER_MAJOR_VERSION: "0"
  SEMVER_VERSION: 0.88.0
  TAG: v0.88.0
  VERSION: 0.88.0
contents:
  packages:
    - '!base-files'
  builds:
    - name: prometheus-operator
      uses: dhi.io/golang:1.25.5-debian13-dev@sha256:a45faad20adc1286eef26b1f30e170b54791c217ce69457784de66b0a13d1fe6
      contents:
        files:
          - url: git+https://github.com/prometheus-operator/prometheus-operator.git#v0.88.0
            checksum: 21974db4687ad80a6ea79af66d410db54510e35e
            path: /go/src/github.com/prometheus-operator/prometheus-operator
            spdx:
              name: prometheus-operator
              version: 0.88.0
              packages:
                - name: prometheus-operator
                  purl: pkg:golang/github.com/prometheus-operator/prometheus-operator@0.88.0
                  license: Apache-2.0
            uid: 0
            gid: 0
      pipeline:
        - name: update go dependencies
          uses: go/bump@v1
          work-dir: /go/src/github.com/prometheus-operator/prometheus-operator
          with:
            deps: []
            download: true
        - name: build
          uses: go/build@v1
          work-dir: /go/src/github.com/prometheus-operator/prometheus-operator
          with:
            ldflags:
              - -X github.com/prometheus/common/version.Version=0.88.0
              - -X github.com/prometheus/common/version.Revision=21974db4687ad80a6ea79af66d410db54510e35e
              - -X github.com/prometheus/common/version.Branch=dhi
              - -X github.com/prometheus/common/version.BuildUser=dhi
              - -X github.com/prometheus/common/version.BuildDate=$(date -u -d @${SOURCE_DATE_EPOCH} +'%F-%T')
            output: ${target.dir}/usr/local/bin/prometheus-operator
            packages: ./cmd/operator/
      outputs:
        - source: ${target.dir}/usr/local/bin/prometheus-operator
          target: /usr/local/bin/prometheus-operator
          uid: 0
          gid: 0
        - source: /opt/docker/sbom/prometheus-operator
          target: /opt/docker/sbom/prometheus-operator
          uid: 0
          gid: 0
  artifacts:
    - name: dhi.io/static:20250419-debian13@sha256:74fc43fa240887b8159970e434244039aab0c6efaaa9cf044004cdc22aa2a34d
      includes:
        - bin
        - etc
        - home
        - lib
        - lib64
        - opt
        - sbin
        - tmp
        - usr
        - var
      excludes:
        - etc/group
        - etc/os-release
        - etc/passwd
        - var/lib/dpkg/status
      uid: 0
      gid: 0
accounts:
  run-as: nonroot
  users:
    - name: nonroot
      uid: 65532
      gid: 65532
  groups:
    - name: nonroot
      gid: 65532
      members:
        - nonroot
os-release:
  name: Docker Hardened Images (Debian)
  id: debian
  version-id: "13"
  version-codename: trixie
  pretty-name: Docker Hardened Images/Debian GNU/Linux 13 (trixie)
  home-url: https://docker.com/products/hardened-images/
  bug-report-url: https://docker.com/support/
annotations:
  org.opencontainers.image.description: A minimal prometheus-operator image
  org.opencontainers.image.licenses: Apache-2.0
entrypoint:
  - /usr/local/bin/prometheus-operator
