metadata:
  display-name: Prometheus Config Reloader
  short-description: Prometheus Config Reloader for use with Prometheus Operator.
  featured: false
  home-url: https://prometheus-operator.dev/
  categories:
    - monitoring-and-observability
