# syntax=dhi.io/build:2-helm3

name: Fairwinds VPA Helm chart 4.x
image: dhi.io/fairwinds-vpa-chart
variant: helm
tags:
  - 4.10.1
platforms:
  - linux/amd64
vars:
  CHART_COMMIT_SHA: 1dc4636b7f2f5d28ff16c01417fe9d432024e180
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_REFERENCE: dhi/helm:3.20.0-debian13-dev@sha256:7069456b86d57f9f2efaf7561c7f78097c6a4382a6e3420d23680ce61a045f34
  KUBE_WEBHOOK_CERTGEN_REFERENCE: dhi/kube-webhook-certgen:1.7.7-debian13@sha256:ef07473c9d86d1d8677f2db5227fb772464661f69464108d0ef1fbf2082c8080
  KUBECTL_REFERENCE: dhi/kubectl:1.35.0-debian13@sha256:c5cbc3a9101f0715d9511c9a722802d74c14697aec1336903a18a2b742b8fb13
  METRICS_SERVER_REFERENCE: dhi/metrics-server-chart:3.13.0@sha256:723ee6f11fd997a5907738efceedb614b6e9ea0153aee46da04fce7577e8ce7e
  SEMVER_MAJOR_MINOR_VERSION: "4.10"
  SEMVER_MAJOR_VERSION: "4"
  SEMVER_VERSION: 4.10.1
  VERSION: 4.10.1
  VPA_ADMISSION_CONTROLLER_REFERENCE: dhi/vpa-admission-controller:1.6.0-debian13@sha256:83d20f237487cf8d2c7e313fc72613867d4ad4d436881cbd8b60ec4ae1eb1043
  VPA_RECOMMENDER_REFERENCE: dhi/vpa-recommender:1.6.0-debian13@sha256:85425f74d443ed46a3d5a14bb8626ad90581a983cd0cf58647a9d609a04bb75a
  VPA_UPDATER_REFERENCE: dhi/vpa-updater:1.6.0-debian13@sha256:9e67d9ef4532bf2443a6a7748fce31c05cf48cf3018d48058bf04e0407b099f6
contents:
  builds:
    - name: fairwinds-vpa-chart
      uses: dhi.io/helm:3.20.0-debian13-dev@sha256:7069456b86d57f9f2efaf7561c7f78097c6a4382a6e3420d23680ce61a045f34
      contents:
        files:
          - url: git+https://github.com/FairwindsOps/charts.git#1dc4636b7f2f5d28ff16c01417fe9d432024e180
            checksum: 1dc4636b7f2f5d28ff16c01417fe9d432024e180
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/stable/vpa
          with:
            chart:
              appRef: vpa-admission-controller
              dependencies:
                - alias: metrics-server
                  condition: metrics-server.enabled
                  name: metrics-server
                  ref: dhi/metrics-server-chart:3.13.0@sha256:723ee6f11fd997a5907738efceedb614b6e9ea0153aee46da04fce7577e8ce7e
              description: Docker Hardened Images Helm chart for Fairwinds VPA
              images:
                - name: vpa-admission-controller
                  ref: dhi/vpa-admission-controller:1.6.0-debian13@sha256:83d20f237487cf8d2c7e313fc72613867d4ad4d436881cbd8b60ec4ae1eb1043
                - name: vpa-recommender
                  ref: dhi/vpa-recommender:1.6.0-debian13@sha256:85425f74d443ed46a3d5a14bb8626ad90581a983cd0cf58647a9d609a04bb75a
                - name: vpa-updater
                  ref: dhi/vpa-updater:1.6.0-debian13@sha256:9e67d9ef4532bf2443a6a7748fce31c05cf48cf3018d48058bf04e0407b099f6
                - name: kube-webhook-certgen
                  ref: dhi/kube-webhook-certgen:1.7.7-debian13@sha256:ef07473c9d86d1d8677f2db5227fb772464661f69464108d0ef1fbf2082c8080
                - name: kubectl
                  ref: dhi/kubectl:1.35.0-debian13@sha256:c5cbc3a9101f0715d9511c9a722802d74c14697aec1336903a18a2b742b8fb13
              name: fairwinds-vpa-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/FairwindsOps/charts
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/stable/vpa
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: helm login
          uses: helm/login@v1
          with:
            registry: dhi.io
        - name: update dependencies
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/stable
          privileged: true
          with:
            chart: vpa
            cmd: dependency update
        - name: lint
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/stable
          with:
            chart: vpa
            cmd: lint .
        - name: package
          uses: helm/package@v1
          work-dir: ${source.dir}/helm-charts/stable
          with:
            chart: vpa
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/fairwinds-vpa/config
